### ISSUE TITLE
Cheatsheet Mode

### ISSUE THREAD

**Issue by juancarlospaco** [fox0430/moe#1022]
# Cheatsheet Mode

- Something like this https://github.com/fox0430/moe/blob/develop/documents/howtouse.md#table-of-contents but on the editor itself.
- 100% immutable, 100% read-only, you can only scroll vertically and read and close it, no options, KISS.

If you are new to Vim or Moe, you have to have the web browser open on the documentation to do anything,
would be nice to have a CheatSheet right in the editor with the basic builtin key combinations.
Can even be the same Markdown on a "readonly view".

This is from another editor, something like this:

![snip](https://user-images.githubusercontent.com/1189414/93316947-36f6c400-f7e3-11ea-8466-073c8b58eb2a.png)

:)

**Comment by fox0430** [comment]
@juancarlospaco 

Do you think the ```:help``` isn't enough?
