### ISSUE TITLE
Improve the performance of highlight updates

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#1076]
Currently, Highlight update performance is poor (especially when scrolling).

**Comment by juancarlospaco** [comment]
Just do not highlight when scrolling?, and highlight again when vertical scrolling stops.

**Comment by fox0430** [comment]
@juancarlospaco 

The cause of this problem is due to the current word highlights and space highlights etc...
I need to reduce this as it updates all the highlights that are each time the cursor moves.
