### ISSUE TITLE
Cursor mode isn't reset 

### ISSUE THREAD

**Issue by SolitudeSF** [fox0430/moe#110]
After exiting the editor cursor will stay in I-beam or block mode, based on which was the last one.

Also cursor isn't properly set on the start of editor. It stays in default mode until mode change occurs.

**Comment by fox0430** [comment]
Thank you feedback. what is the terminal emulator you are using?

**Comment by fox0430** [comment]
@SolitudeSF 
I made it possible to set the cursor shape in the configuration file. ( #132 )
Do you know any other good ideas?

**Comment by SolitudeSF** [comment]
neovim restore cursor shape on exit, but i cant find a relevant code.
simple workaround would be to just reset terminal on exit, but i dont know if thats a good practice.

**Comment by SolitudeSF** [comment]
okay, xterm spec defines `CSI Ps SP q` sequence, that sets a cursor shape, where `Ps` is a 0-6 number corresponding to different cursor shapes, and 0 is the same as 1. VTE spec defines 0 as default terminal cursor shape. Si this will work in all terminals that respect that spec, like every VTE terminal or kitty. So `\e[0 q` is all that needed. If the terminal doesn't support it, it stays at blinking block.

**Comment by fox0430** [comment]
@SolitudeSF 
Thank you advice!

**Comment by unihernandez22** [comment]
Same
