### ISSUE TITLE
Haskell highlighting

### ISSUE THREAD

**Issue by uninhm** [fox0430/moe#1116]

**Comment by kevinmatthes** [comment]
There is an infamous edge case of valid Haskell source code:  Literate Haskell (`*.lhs`).  It is designed to be both LaTeX *and* Haskell.  How should this be handled?

**Comment by fox0430** [comment]
@kevinmatthes 

Currently, I don't plan on doing this work. I think Haskell should be supported by LSP.
Of course, welcome to PR.

**Comment by kevinmatthes** [comment]
@fox0430

Okay!
