### ISSUE TITLE
visual block line-begin insert does not allow backspacing

### ISSUE THREAD

**Issue by JorySchossau** [fox0430/moe#1309]
Control codes show up when trying to backspace in this specific insert mode. I haven't dived in yet to figure out why this happens, but figured I'd at least record it.

Reproduce:
```
ctrl-v (block visual mode)
I (insert at beginning of line)
<type something>
<now try to backspace>
```

Observed:
typed: `asdf<backspace><backspace>`
shown: `asdf^?`

All other insert modes I've tried work okay, so I suspect it's not an input library / systematic issue.

**Comment by fox0430** [comment]
@JorySchossau

Thank you for your feedback! I will fix it.
