### ISSUE TITLE
In 'insert' mode, Moe crashes every time I hit enter or paste multiline text

### ISSUE THREAD

**Issue by brett-mahar** [fox0430/moe#1370]
This is with the version built with 'nimble build' on archlinux/pinebookPro:
Nim Compiler Version 1.4.8 [Linux: arm64]

When pasting, Moe exits back to shell, I get the error scattereed across the screen:

/home/brett/.NIM/moe/src/moe.nim(73) moe
/home/brett/.NIM/moe/src/moe.nim(56) main
/home/brett/.NIM/moe/src/moepkg/insertmode.nim(109) insertMode
/home/brett/.NIM/moe/src/moepkg/editor.nim(295) keyEnter
/usr/lib/nim/system/fatal.nim(49) sysFatal
Error: unhandled exception: value out of range: -1 notin 0 .. 9223372036854775807 [RangeDefect]

Let me know if you want more information.

In case it matters, my config:

[Standard]
theme = "dark"
number = false
currentNumber = false
cursorLine = false
statusLine = true
tabLine = false
syntax = true
indentationLines = false
tabStop = 2
autoCloseParen = false
autoIndent = false
ignorecase = true
smartcase = true
disableChangeCursor = false
defaultCursor = "noneBlinkBlock"
normalModeCursor = "noneBlinkBlock"
insertModeCursor = "blinkIbeam"
autoSave = false
liveReloadOfConf = false
incrementalSearch = true
popUpWindowInExmode = true
autoDeleteParen = false
smoothScroll = false

[Clipboard]
enable = false

[BuildOnSave]
enable = false

[TabLine]
allBuffer = false

[StatusBar]
multipleStatusBar = false
merge = false
mode = true
filename = false
chanedMark = false
line = true
column = false
encoding = true
language = false
directory = false
gitbranchName = false
showGitInactive = false
showModeInactive = false

[Highlight]
currentLine = false
reservedWord = ["TODO", "WIP", "NOTE"]
replaceText = false
pairOfParen = true
fullWidthSpace = true
trailingSpaces = true
currentWord = true

[AutoBackup]
enable = false

[QuickRun]
saveBufferWhenQuickRun = false

[Notification]
screenNotifications = true
logNotifications = false
autoBackupScreenNotify = false
autoBackupLogNotify = false
autoSaveScreenNotify = false
autoSaveLogNotify = false
yankScreenNotify = true
yankLogNotify = false
deleteScreenNotify = true
deleteLogNotify = false
saveScreenNotify = true
saveLogNotify = false
quickRunScreenNotify = false
quickRunLogNotify = false
buildOnSaveScreenNotify = false
buildOnSaveLogNotify = false
filerScreenNotify = true
filerLogNotify = false
restoreScreenNotify = true
restoreLogNotify = false

[Filer]
showIcons = true

[Autocomplete]
enable = true

[Persist]
exCommand = true
search = true
cursorPosition = true

[Debug.WindowNode]
enable = false

[Debug.EditorView]
enable = false

[Debug.BufferStatus]
enable = false

[Theme]
baseTheme = "dark"

editorBg = "default"
lineNum = "gray54"
lineNumBg = "default"
currentLineNum = "teal"
currentLineNumBg = "default"

statusLineNormalMode = "white"
statusLineNormalModeBg = "darkOrange3_1"
statusLineModeNormalMode = "black"
statusLineModeNormalModeBg = "white"
statusLineNormalModeInactive = "darkOrange3_1"
statusLineNormalModeInactiveBg = "white"

statusLineInsertMode = "white"
statusLineInsertModeBg = "darkOrange3_1"
statusLineModeInsertMode = "black"
statusLineModeInsertModeBg = "white"
statusLineInsertModeInactive = "darkOrange3_1"
statusLineInsertModeInactiveBg = "white"

statusLineVisualMode = "white"
statusLineVisualModeBg = "darkOrange3_1"
statusLineModeVisualMode = "black"
statusLineModeVisualModeBg = "white"
statusLineVisualModeInactive = "darkOrange3_1"
statusLineVisualModeInactiveBg = "white"

statusLineReplaceMode = "white"
statusLineReplaceModeBg = "darkOrange3_1"
statusLineModeReplaceMode = "black"
statusLineModeReplaceModeBg = "white"
statusLineReplaceModeInactive = "darkOrange3_1"
statusLineReplaceModeInactiveBg = "white"

statusLineFilerMode = "white"
statusLineFilerModeBg = "darkOrange3_1"
statusLineModeFilerMode = "black"
statusLineModeFilerModeBg = "white"
statusLineFilerModeInactive = "darkOrange3_1"
statusLineFilerModeInactiveBg = "white"

statusLineExMode = "white"
statusLineExModeBg = "darkOrange3_1"
statusLineModeExMode = "black"
statusLineModeExModeBg = "white"
statusLineExModeInactive = "darkOrange3_1"
statusLineExModeInactiveBg = "white"

statusLineGitBranch = "white"
statusLineGitBranchBg = "darkOrange3_1"

# tab line
tab = "white"
tabBg = "default"
currentTab = "white"
currentTabBg = "darkOrange3_1"

# command  bar
commandBar = "gray100"
commandBarBg = "default"

# error message
errorMessage = "red"
errorMessageBg = "default"

# search result highlighting
searchResult = "green"
searchResultBg = "seaGreen1_2"

# selected area in visual mode
visualMode = "gray100"
visualModeBg = "purple_1"

# color scheme
defaultChar = "gray84"
#defaultChar = "lightGoldenrod2_2"
#gtKeyword = "mistyRose3"
gtKeyword = "lightGoldenrod2_2"
gtFunctionName = "gold1"
gtBoolean = "yellow"
gtStringLit = "yellow"
gtSpecialVar = "green"
gtBuiltin = "yellow"
gtDecNumber = "aqua"
gtComment = "seaGreen1_2"
gtLongComment = "seaGreen1_2"
gtWhitespace = "gray"
gtPreprocessor = "green"

# filer mode
currentFile = "gray100"
currentFileBg = "teal"
file = "gray100"
fileBg = "default"
dir = "darkOrange3_1"
dirBg = "default"
pcLink = "teal"
pcLinkBg = "default"

# pop up window
popUpWindow = "gray100"
popUpWindowBg = "black"
popUpWinCurrentLine = "darkOrange3_1"
popUpWinCurrentLineBg = "black"

# replace text highlighting
replaceText = "default"
replaceTextBg = "red"

# pair of paren highlighting
parenText = "default"
parenTextBg = "darkOrange3_1"

# highlight other uses current word
currentWord = "default"
currentWordBg = "gray"

# highlight full width space
highlightFullWidthSpace = "red"
highlightFullWidthSpaceBg = "red"

# highlight trailing spaces
highlightTrailingSpaces = "red"
highlightTrailingSpacesBg = "red"

# highlight reserved words
reservedWord = "white"
reservedWordBg = "gray"

# configuration mode
currentSetting = "gray100"
currentSettingBg = "teal"

# highlight current line background
currentLineBg = "gray27"

**Comment by fox0430** [comment]
@brett-mahar 

Thank you for your feedback!
This is a bug. I will fix it.

**Comment by brett-mahar** [comment]
Thank you, sir Fox!
