### ISSUE TITLE
Can not install and build

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#138]
It is because the ncurses package can't install.

**Comment by SolitudeSF** [comment]
i updated [my PR](https://github.com/rnowley/nim-ncurses/pull/17/files#diff-74ff174d2c2f75ead8477e746e9e5d6eL2) to include the fix to the nimble file

**Comment by fox0430** [comment]
@SolitudeSF We forked ncurses as a temporary solution (#139)
