### ISSUE TITLE
Crash when issuing "help" command

### ISSUE THREAD

**Issue by ci4ic4** [fox0430/moe#1515]
I just rebuilt moe on a Ubuntu Aarch64 and on a NetBSD-current Amd64 machines. While 'nimble test' completed without errors, running simple ':help' crashes moe on both systems identically. Here is the truss before the crash, if it is of any use:

`/home/xci/src/moe/src/moe.nim(69) main
/home/xci/src/moe/src/moepkg/help.nim(284) helpMode
/home/xci/src/moe/src/moepkg/editorstatus.nim(531) update
/home/xci/src/moe/src/moepkg/editorview.nim(405) update
/home/xci/src/moe/src/moepkg/editorview.nim(339) writeAllLines
/home/xci/src/moe/src/moepkg/highlight.nim(23) []
/usr/pkg/nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: index -1 not in 0 .. 0 [IndexDefect]
06 moe      __wait450(0x2eff, 0x7f7ffff2d31c, 0x1, 0) = 0`

The terminal is left in a weird state; even 'stty sane' can't fully repair it; as I use tmux, I kill the frame and get a new one.

**Comment by fox0430** [comment]
@ci4ic4 

Thank you for the bug report.

It seems to be no problem on ArchLinux Amd64.
What are versions of Nim and moe?
Did you open buffers (files) before opening help?

**Comment by ci4ic4** [comment]
It happens only if you haven't opened a file yet.
Otherwise, 
```
./src/moe/moe --version
moe v0.4.0
Build type: Debug
```

```
$ nim --version
Nim Compiler Version 1.6.8 [Linux: arm64]
Compiled at 2022-10-18
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

and also 

```
$ nim --version
Nim Compiler Version 1.6.8 [NetBSD: amd64]
Compiled at 2022-11-01
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

However, if you have opened a file and use :help, the help text appears in the second frame (for some reason only five lines are displayed in the NetBSD case, more seen under Linux), and you get the same crash if you scroll down the help window, past line 46 in the NetBSD case and past line 77 on the Linux case.

**Comment by fox0430** [comment]
@ci4ic4 

Thank you for more info.
I tried again and it was reproduced. I'll fix it soon.

Thank you.
