### ISSUE TITLE
Suggestion:  Dependabot

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1516]
@fox0430

At the moment, I am working on the obsolete conversions and redundant imports.  Thereby, I noticed that some of the Actions the CI requires have received major updates.  Some of the current versions are not supported anymore, thus, the CI might break if not updated.

I would like to suggest to submit a separate Pull Request with the version updates such that the CI will continue to work.

In the long term, would Dependabot be useful in order to keep all dependencies up-to-date?  Once configured, it will submit Pull Requests with the respective updates.  At option, you can write it an email (many mailing programs name this "reply to list") in order to instruct it to merge the update.  I previously worked with Dependabot in some other repositories, especially to track GitHub Actions, so I can prepare an initial setup, if you would like to try out this feature.  I therefore would need to know which settings are preferred, especially:

* the frequency of checks for updates (I recommend daily in order to do not miss important updates.)
* the time when to check for updates (I highly recommend specifying a time; otherwise, the time will be random.  This can be either some UTC time or a time relative to a given time zone.)

Shall I prepare an initial setup for Dependabot?

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you for suggestion.
That’s a good idea. I want to use Dependabot.

**Comment by kevinmatthes** [comment]
@fox0430

Okay, I am going to make a Pull Request!
