### ISSUE TITLE
Discussion:  CFF Data

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1529]
> This issue originates from #1523.

As I announced in #1523, this is the issue for the discussion of the initial CFF meta data.

The setup will include:

- the CITATION.cff;
- a GitHub Action for automatic validation; and
- a badge for the README referring to the CFF validation Action.

Most of the meta data is obvious.  I only need the following information in order to prepare the Pull Request:

- author information:  @fox0430, I would initially add you as the sole author and only with your GitHub alias.  Many projects handle the authorship in terms of CFF differently; some consider it a list of contributors, others limit it the original author, some add the project's community as the anonymous group who co-authored the project.  Which option would you prefer?
- artifact repository:  is there any website which stores precompiled binaries of Moe?

The list of references can be curated on demand once the setup is completed.

A note on the maintenance effort:  the release date as well as the version need to be updated on release.  These are two succeeding lines in the CITATION.cff.  I can also add an automation to increment the version numbers on release; unfortunately, it does not support release dates, as far as I know.

**Comment by fox0430** [comment]
@kevinmatthes 

- Author information: At first, the list of contributors.

- Artifact repository: If we need a website, https://editor.moe? but this website was created by Hugo, I don't know if we can easily store binaries.

**Comment by kevinmatthes** [comment]
@fox0430

No problem.  CFF accepts up to four different URLs, I already planned to set the main URL to `editor.moe` as this is also named on the project's landing page.  The source code repository is obviously this GitHub repository.  The other two URLs are optional.

**Comment by fox0430** [comment]
@kevinmatthes 

Good. GitHub repo and `editor.moe` would be fine.

**Comment by kevinmatthes** [comment]
@fox0430 Alright, I will prepare the PR.
