### ISSUE TITLE
Discussion:  CHANGELOG?

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1542]
@fox0430

Should we add a CHANGELOG to Moe?  There are also utilities which assemble the CHANGELOG on release and write the GitHub release notes -- in addition to GitHub's built-in release note generation.

**Comment by fox0430** [comment]
@kevinmatthes 

I didn’t know GitHub’s bulletin release note generation.
It looks convenient.

**Comment by kevinmatthes** [comment]
@fox0430

I agree with you that the built-in release note generation is a very comfortable feature.  GitHub will automatically fetch the titles of the PRs merged since the last release was published.  I prefer this feature to other release generators and use it for my projects, as well.

Do these release notes suffice for the documentation of changes or should we create a dedicated CHANGELOG file in the repository's root?

**Comment by fox0430** [comment]
@kevinmatthes 

It might be better to have the CHANGELOG file in the repository’s root.

**Comment by kevinmatthes** [comment]
@fox0430

There are several maintenance strategies for CHANGELOGs.  Some projects prefer, for instance, that the contributors add the entries corresponding to their changes by submitting them in the same PR.  Other projects limit the CHANGELOG editing to the maintainers and collaborators.

Which strategy would you prefer for Moe?

**Comment by fox0430** [comment]
@kevinmatthes 

Limit the CHANGELOG editing to the maintainers and collaborators for now.

**Comment by kevinmatthes** [comment]
@fox0430

Shall I prepare an initial setup for the changes since version 0.3.0's release?

**Comment by fox0430** [comment]
@kevinmatthes 

That would be nice.

**Comment by kevinmatthes** [comment]
@fox0430

I am working on it, I am going to submit a PR tomorrow.
