### ISSUE TITLE
Discussion:  On-Release CHANGELOG Assembly

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1545]
> This issue is related to #1542 and #1544.

In #1542, we discussed two possible workflows for keeping CHANGELOGs up-to-date.  The first one is that after each merged PR, the maintainers and collaborators add a new entry to the CHANGELOG.  The second one is that contributors always add their preferred entries to the CHANGELOG themselves.  Both have their disadvantages.

The first workflow is very time-consuming.  After each PR, the maintainers and collaborators would have to figure out how the introduced changes could be summarised best and need to add the resulting entry to the CHANGELOG.  Obviously, this requires working through the changes once again in case that the PR's description should not be very informative.  The time required for this cannot be used to develop new major features of the project and will, hence, slow down the development in the long term.

The second workflow challenges this disadvantage by handing the responsibility for the creation of the new CHANGELOG entry over to the respective contributors.  They will then not only submit their changes but also add a brief summary directly to the CHANGELOG file.  The disadvantage here is the risk of Merge Conflicts.  Large projects like [Lapce](https://github.com/lapce/lapce) suffer from this notably.  Let us therefore consider the following example.  Three contributors A, B, and C submit PRs to a project with all three PRs originating from the same repository state.  All contributors edit the CHANGELOG by adding appropriate entries, this is, they edit the very same line.  When A's PR gets merged at first, the PRs of B and C will receive Merge Conflicts as now, they attempt to overwrite A's CHANGELOG entry with their own entries.  After resolving the conflicts, both PRs can be merged again with, say, B's PR being the next one merged.  C would have to resolve the resulting Merge Conflicts, again.  In the long term, this does not only slow down the development, it might be also very discouraging for the contributors.

The solution to the disadvantages of both workflows is the following third one.  The CHANGELOG is an artifact which is neither edited by the maintainers and collaborators nor by the contributors.  A software tool will take care about shelving in the new entries.  These are stored as unique files, named fragments, in a central storage.  On release, the main maintainer instructs the software to collect all fragments and to insert them into the CHANGELOG.  The software will sort them by category and add a title for the new version, as well.  My suggestion is to introduce this workflow for Moe, as well.

For this purpose, there are plenty FOSS tools available, most of them only accept ReStructuredText CHANGELOGs -- such as the one I proposed in #1544.  I worked with [Scriv](https://github.com/nedbat/scriv), so far, which also accepts Markdown CHANGELOGs (which tend to become a little ugly due to some rendering issues, thus the RST version is also for Scriv preferably).  The software is licensed MIT and written in Python 3.  To install, run `pip3 install scriv`.  The fragments are stored in the directory `changelog.d/` in the repository root, by default, into which the CLI will insert the new fragments by calling `scriv create --edit`.  This will open a template for a new fragment in Moe, one just needs to add the information.  The file name will consist of a timestamp, the user name and the current branch making the fragment unique in order to prevent Merge Conflicts.  When the new version is ready for release, one maintainer calls `scriv collect` such that Scriv will paste all fragments into the CHANGELOG.  It will create the version header for the Keep a Changelog convention, as well, in addition to a hook for an optional table of contents.

With Scriv, the workflow will become as follows.  The contributor submits the PR as usually.  When the PR was created, the contributor commits the fragment; the current style of the CHANGELOG demands to know the number of the respective PR.  When merged, the changes will be applied and the new fragment is added to the fragment storage.  On release, the fragments will be collected and removed after pasting their contents to the CHANGELOG, leaving an empty directory to be filled again for the next release.  This procedure would reduce the maintenance effort for the CHANGELOG to a sane minimum while ensuring the entries to be complete and informative.

My suggestion is to setup Scriv for Moe.  I would therefore suggest to add the configuration to #1544.  @fox0430, do you agree?

**Comment by kevinmatthes** [comment]
@fox0430

I am sorry, Scriv is Apache-2.0.  Technically, this does not make any difference; both licenses work with Moe's GPL-3.0.

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you for the details.
I asked you to open an issue for CHANGELOG tools, but I'm a little hesitant to introduce new tools for CHANGELOG now.
Please let me think about it. and if you have any other advice or opinions, please let me know.

**Comment by kevinmatthes** [comment]
@fox0430

Okay, no problem.

**Comment by kevinmatthes** [comment]
@fox0430

After some hours of researching, testing and debugging, I finally found a way how to turn the CHANGELOG assembly -- together with a version number increment for all relevant files -- into a GitHub Action workflow.  Here are the references:

* the repository:  https://github.com/kevinmatthes/git-aliases-f18
* the workflow:  https://github.com/kevinmatthes/git-aliases-f18/blob/main/.github/workflows/release-patch.yml
* the software requirements:  https://github.com/kevinmatthes/git-aliases-f18/blob/main/requirements.txt

### What is the referenced repository supposed to do?

This repository is the source code of a CLI to configure Git alias commands.  This is useful to configure the preferred aliases for new user accounts.  It is also a simple project to test some GitHub utilities.

### What does the GitHub Action workflow do?

First of all, it will download all required software.  This includes the CLIs for the actual version increment (bump2version) and the CHANGELOG assembly (Scriv) as well as the build system (Just).  Just is a UNIX make replacement, written in Rust; it could also have been something totally different, the important thing is the idea of this Action, not the employed build routine manager.

When all software tools are installed, the user account for the commit will be prepared.  I decided to use the GitHub Action bot who / which I considered a reasonable choice.  I would suggest to use this account for an implementation for Moe, as well, in case the automation would be an option.

Next, bump2version increments all version numbers.  This is very useful and reduces the maintenance effort for a new release; it only requires a self-maintaining configuration file.  It contains the current version number which will be updated on call to bump2version, thus, it can be considered self-maintaining.  This step is optional but works marvelously together with Scriv.  Scriv will then collect the fragments and assemble the CHANGELOG.  These two steps are encapsulated by the build routine, Just, but can be also run separately with a `run:` instruction in the workflow; this is why the actual build routine does not matter.

Finally, the changes are committed and pushed back to the repository.  This workflow therefore needs `contents: write` in its permissions.

### How to invoke the workflow?

This workflow is configured for manual dispatch.  To run such a workflow, visit Actions → <name of the workflow> → Run workflow → select the correct branch → Run workflow (green button).  This requires the appropriate privileges for the respective repository.

The workflow will take care about everything and commit the changes.  One just needs to merge the corresponding PR, in case the changes were committed to some other branch than the default one.

**Comment by kevinmatthes** [comment]
@fox0430

The described GitHub Action approach would keep the software requirements virtual dependencies; no installation on an actual machine is required as the calls to them take place only during the workflow's execution.  They are going to be installed on the GitHub runner.

From the license point of view:  all requirements work with Moe's GPL-3.0.  Scriv and the Python 3 dependency installer are both Apache-2.0; bump2version, checkout, the Python setup, the Git user configuration, and the push to the repository are all MIT.  If required, the Just installer would be Apache-2.0 OR MIT, Just itself is least problematic due to being CC0-1.0.

**Comment by fox0430** [comment]
@kevinmatthes 

It looks great. The GitHub Actions approach is the solution I wanted.

**Comment by kevinmatthes** [comment]
@fox0430

Okay, I am going to update #1544 with the corresponding changes.
