### ISSUE TITLE
[Question] Scriv Fragment Creation Workflow?

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1550]
@fox0430

Since the software requirements for the release workflow, bump2version and Scriv, are kept truly virtual, there is no need to install them.  But in order to create a Scriv CHANGELOG fragment for a PR, its templates might be useful.

Scriv assumes a certain structure for a fragment.  In order to not violate this structure, Scriv can create you a fresh fragment with the expected categories as comments.

Shall I create a workflow to generate fresh Scriv fragments with explanatory comments and the expected categories predefined in order to make it easier to add the corresponding fragment to a PR?

**Comment by fox0430** [comment]
@kevinmatthes 

It looks convenient. I want it.
