### ISSUE TITLE
[Bug Report] Flickering Cursor in Files with 1000+ Lines

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1554]
@fox0430

When working on #1553, I edited some files with more than one thousand lines.  With the setting `disableChangeCursor = false` in my settings for Moe, the cursor stays solid (i.e. non-blinking) during the editing process.  I know that due to the debug symbols in test compilations, the cursor will always flicker when moving around in the file because the debug compilation is less performant in comparison to the release build.

But if even the release build starts to have a flickering cursor when editing large files, this might indicate that there could be a performance bottle neck somewhere.

I edited the following files:

- src/moepkg/color.nim (flickers only in EX mode)
- src/moepkg/settings.nim (always flickering)

**Comment by fox0430** [comment]
@kevinmatthes 

It seems that it probably doesn't reproduce in my environment.
As a performance issue, What CPU are you using?

**Comment by kevinmatthes** [comment]
@fox0430

The problem occurred with an AMD Ryzen 5700U with hyper-threading enabled, i.e. 16 cores.  I executed the latest available release build of Moe at the time of the issue submission, compiled using `nimble install -y moe@#head`.

To reproduce, I recommend to first of all disable the cursor modification by the editor and to set the terminal's cursor to non-blinking.  In a small file, say, `src/moepkg/flags.nim`, the cursor will not disappear for a short moment ("flicker") when moving to the succeeding character in the same line.  But it will when navigating in larger files like `src/moepkg/settings.nim`.

**Comment by fox0430** [comment]
@kevinmatthes 

Actually, I don't fully understand this problem. Certainly, the cursor flickering, but it is the same in the single line file...

I tested and recorded it on my laptop (Intel Core i5-1130G7).
Is this the same as yours?

https://github.com/fox0430/moe/assets/15966436/d0cfff6c-c7c2-432d-8f27-89f0d99aa780

**Comment by kevinmatthes** [comment]
@fox0430

I assumed that this flickering might have indicated some sort of performance issue / bottleneck.  But now, it seems as if the issue would have resolved in the meantime due to the recent improvements; I cannot reproduce the flickering anymore.  Thus, I close this issue as completed, now.
