### ISSUE TITLE
[Bug Report] Cursor does not Change Back to Normal

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1555]
@fox0430

When editing some files with Moe in the KDE terminal `konsole`, v20.12.3, I start with a solid cursor (i.e., it is not blinking).  If Moe is allowed to change cursors, the cursor will start to blink as soon as the editor runs.  When quitting Moe regularly by using one of `:WQ`, `:Q`, and `:Q!`, the cursor still keeps blinking after the editor is left.  Changing back to the normal solid cursor requires restarting the terminal.

I consider this a bug since the expectation would be that the cursor will only blink within the editor and returns to solid state after leaving it.

(I apologise for this late bug report; I disabled the cursor changing when I started to use Moe and forgot to report this bug.  I am sorry.)

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you for the bug report.

Do you mean that doesn't change back to the kconsole default cursor shape after quitting moe?
And Did you change `Standard.defaultCursor` setting?

A few years ago, I didn't know how to restore the terminal default cursor shape.
I'll research it again.

**Comment by kevinmatthes** [comment]
@fox0430

> Do you mean that doesn't change back to the kconsole default cursor shape after quitting moe?

Yes, this is correct.

> And Did you change `Standard.defaultCursor` setting?

No, the setting is still equal to the example configuration this repository provides; `defaultCursor = "blinkBlock"`.

**Comment by fox0430** [comment]
@kevinmatthes 

Do you know an application that restores the cursor shape after quitting?

I set the default to the beam cursor and started NeoVim and quit, but it doesn't return to the beam (Still the block cursor after quitting it).
Vim and Nano remained Beam even on applications (Always beams).

It may be helpful if there is an application that restores the cursor shape on exit.

**Comment by kevinmatthes** [comment]
@fox0430

I am sorry, I do not know any application which resets the cursor after editing it.  In fact, Moe was the very first application at all I experienced changing the cursor style.

But I found something which might be helpful:  https://github.com/rust-cli/anstyle/blob/main/crates/anstyle/src/reset.rs#L21.  This is a Rust library which allows for the formatting of output written to `stderr` / `stdout` by the usage of ANSI escape codes.  When the text shall be reset, the escape code defined in the line I linked is written to the respective output stream.  Would this reset code be an option?

**Comment by fox0430** [comment]
@kevinmatthes 

I found a solution (#1727). but it may not work on kconsole...

**Comment by kevinmatthes** [comment]
@fox0430

Thank you for your work on that!  I assume that it should work because the reset code works for colours in KDE Konsole when used by the Rust library.  And even if it should not work with that particular terminal -- a partial solution is always a good progress.
