### ISSUE TITLE
White text on white background on terminals with white background

### ISSUE THREAD

**Issue by xoich** [fox0430/moe#1563]
Hello, I tried the editor, but I have a terminal with a white background and text color in moe is also white. I tried changing the theme, but vivid and light themes also have white text. Vim does not have this problem, it starts automatically with the correct text color both on black and white terminals.

**Comment by fox0430** [comment]
@xoich 

Thank you for the bug report.

Is it completely unreadable in your environment?
I tried on xterm, and on my environment it is like this

![moe](https://user-images.githubusercontent.com/15966436/209177443-4d2eceac-dd66-41e7-b727-0c9974c89923.png)

**Comment by xoich** [comment]
hi @fox0430 interesting, I have urxvt-unicode and it's white on white for me, with invisible text.

Edit: this is on txt files with no syntax highlighting. On nim files a lot of the text is still completely unreadable white, but there is also some readable text when it's colored (although it's still too light)

**Comment by xoich** [comment]
![shot](https://user-images.githubusercontent.com/5114966/209188267-8320f518-e2c1-46d7-827f-bbd36d9c9fef.png)

**Comment by fox0430** [comment]
@xoich 

Could you tell me the your urxvt color settings?

**Comment by xoich** [comment]
@fox0430 this is the only setting I changed on urxvt, it only changes the font size:

URxvt.font: xft:mono:size=18

**Comment by fox0430** [comment]
@xoich 

Thank you. I tried the same settings. It seems that light gray becomes completely white on the default settings urxvt.

I will adjust light theme colors.

### xterm
![xterm](https://user-images.githubusercontent.com/15966436/209200422-d179e628-2970-461d-8261-ef1ad4712b12.png)


### urxvt
![urxvt](https://user-images.githubusercontent.com/15966436/209200385-f112da11-f878-490b-a24c-0f9499ca45ae.png)

**Comment by xoich** [comment]
thank you! Shouldn't moe work well also with the default theme? Somebody who tries it out might give up if they see nothing when it starts.

**Comment by fox0430** [comment]
@xoich 

You are correct. I will consider a default theme that supports both white and black backgrounds.
