### ISSUE TITLE
[Bug Report] Editor Breaks in C Language Mode if Line Begins with Slash Character

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1568]
Happy New Year, @fox0430!

First of all, I am sorry that I did not submit a suggestion for the Shell syntax highlighting, yet.  The days before Christmas are always somehow chaotic and I did not had the time to take care for the implementation.  I will suggest a basic implementation by the end of the month.

The bug this issue is about occurred when I revisited other syntax highlighting implementation in order to ensure that nothing will break.  Therefore, I created a blank C header file for testing purposes, `test.h`.  I tried to add a comment in the first line by typing `/` in Insert Mode.  This broke the editor.  I found out so far that a crash will happen if the slash starts the line, any preceding characters seem to prevent the editor from breaking.

**Comment by fox0430** [comment]
@kevinmatthes 

> First of all, I am sorry that I did not submit a suggestion for the Shell syntax highlighting, yet. The days before Christmas are always somehow chaotic and I did not had the time to take care for the implementation. I will suggest a basic implementation by the end of the month.

No problem! looking forward to it.

> The bug this issue is about occurred when I revisited other syntax highlighting implementation in order to ensure that nothing will break. Therefore, I created a blank C header file for testing purposes, `test.h`. I tried to add a comment in the first line by typing `/` in Insert Mode. This broke the editor. I found out so far that a crash will happen if the slash starts the line, any preceding characters seem to prevent the editor from breaking.

Thank you for the bug report. I have reproduced it too.  It's a critical bug and I'll fix it.

**Comment by fox0430** [comment]
@kevinmatthes 

 Do you know the meaning of `/` in C?
I found the cause of this bug but I don't know which [TokenClass](https://nim-lang.org/docs/highlite.html#TokenClass) to use...

**Comment by kevinmatthes** [comment]
@fox0430

Basically, `/` in C is a builtin operator.

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you! I'll use `gtOperator`.
