### ISSUE TITLE
[Bug Report] Editing Files Opened by `:e` Crashes the Editor

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1581]
@fox0430

I am using the latest available state of Moe, installed using `nimble install -y moe@#head` just a few minutes ago.

Consider the following situation:  there is directory named `src` containing two files, `a.nim` and `b.nim`.  Now, call `moe src/a.nim` to start the editor.  Without making any changes to `a.nim`, do `:VS` and `:e src/b.nim` and switch to insert mode in `b.nim` which should be shown on the right half of the screen.  Try to insert a single line break in `b.nim`.  This will crash the editor.

I could reproduce this behaviour so far in both Rust and C language modes, as well, thus, I guess that the language configuration is not responsible for this bug.  As the scenario to edit two files in one session next to each other is a very common use case in my opinion, I would consider this bug critical.

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you for bug reports. Might be a little buggy in currently affected by #1571.
It may be inconvenient, but I will fix it as soon as I find it.
