### ISSUE TITLE
[Discussion] Special Use Cases of Shell Command Execution

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1602]
@fox0430

I found the following two use cases of the `:!` command being pretty common in my development workflow:
- `:!echo` to see the recent terminal output, for example from a `grep` command for lines to edit
- `:!man <something>` to view a certain manual page, especially for C standard library functions

Both can be made easily into dedicated commands on their own as they are special cases of the regular command execution.  The first one is simply `shellCommand` without line 1085 (https://github.com/fox0430/moe/blob/develop/src/moepkg/exmode.nim#L1085) and could be named `bg`, for example, as it is the opposite action to the UNIX command `fg`.  Although Moe explicitly supports `Ctrl + Z` out of the box, a dedicated internal command might avoid forgetting about a paused Moe instance in the background.

The second one is another special case of `shellCommand` without the lines 1086 and 1087 (https://github.com/fox0430/moe/blob/develop/src/moepkg/exmode.nim#L1086; https://github.com/fox0430/moe/blob/develop/src/moepkg/exmode.nim#L1087) as the editor perspective would be restored automatically when `man` returns.  The command could be named `man` and take the arguments for `man` as parameters.  As it is already officially recommended to run Moe in a Linux environment, the presence of the `man` executable could be considered a sane assumption.

I would like to discuss whether it would be useful to give those two use cases commands on their own.

**Comment by fox0430** [comment]
@kevinmatthes 

I think it's fine to add these commands. Both are easy to add and I think some people want to use them.

**Comment by kevinmatthes** [comment]
@fox0430

Okay, I will prepare a PR. :+1:

**Comment by kevinmatthes** [comment]
@fox0430

In a later step, we might also create a manual page for Moe; calling `:man` without any further arguments could then open up Moe's manual page.  At the moment, I made calling `:man` an invalid command which does not do anything.  At option, I could also make it invoke `man man`.
