### ISSUE TITLE
[Feature] [Discussion] CODEOWNERS

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1613]
@fox0430

Reviewing the changes of others, suggested as PRs, is in general a good idea in order to be able to discuss further adjustments, for instance.  There is a configuration file to ensure that every PR, except from certain people, will be reviewed.  This configuration file is named `.github/CODEOWNERS` and controls which files cannot be edited without a following review by the respective owner(s).  This is thus a security feature and applied in the repositories of the official GitHub Actions, for example.  The people maintaining a repository can thereby control which teams need to review what; the owner, for example, might always want to review anything while the documentation team would have a major interest to stay up-to-date regarding the state of the project's manual.

I noticed that in the latest PRs, you always self-requested a review of the changes if you were not the original author.  Configuring CODEOWNERS would hence automatically request a review from you which would save time.  If you would submit a PR to this repository with CODEOWNERS configured somehow, you would not need to self-review your changes.

There are two downsides of CODEOWNERS I would like to mention:
- Depending on the configuration, you might be unable to receive GitHub's YOLO achievement (merging changes without a previous review) for the respective repository due to the intention of CODEOWNERS.
- Depending on the configuration, Dependabot's "Mail Merging" feature might become unavailable.  With "Mail Merging", I mean the possibility to write an email to Dependabot telling it to merge the changes without needing to sign-in on GitHub.  Bors should still work, though (which is also nice way to hide the Dependabot PRs from GitHub's automatic release notes).

**Comment by fox0430** [comment]
@kevinmatthes 

I didn't know CODEOWNERS. I was considering using an Action like this https://github.com/kentaro-m/auto-assign-action, but CODEOWNERS  may be sufficient.

**Comment by kevinmatthes** [comment]
@fox0430

I just had a look at the Action you mentioned; both approaches will have mostly the same effects.  The main differences are the configuration effort and the change limitation.

I assume that you would like to be asked for a review for everything in this repository, right?  Then, CODEOWNERS just requires one effective line:  `* @fox0430`.  If you would like to set it up, just paste the following to a new file named `.github/CODEOWNERS`:

```
######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2017─2023 fox0430                                            ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

* @fox0430

################################################################################
```

This will do the job and also fulfill the requirements of the GPL-3.0.  (Adding the license header to each is what I consider a best practice.)

**Comment by kevinmatthes** [comment]
@fox0430

Just like `dependabot.yml`, CODEOWNERS is a special configuration file with a different meaning whether the respective repository is the original or a fork.  In order to avoid trouble with the configuration, it might be better if you as the repository owner would create the file -- if CODEOWNERS is your preferred option.

The suggested configuration will ask you to review every PR of which you are not the author.

**Comment by fox0430** [comment]
@kevinmatthes 

Okay, I’ll create a PR soon. Thank you.
