### ISSUE TITLE
[Bug Report] Rust Highlighting Crashes on Wrapped Lines with Different Token Types

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1713]
### Version

Nightly

### Category

Major — The software does not fulfill the task it is designed for.

### Steps to Reproduce

```
echo 'assert_eq!(agd.tokens(), &[Comment, LineFeed, LineFeed, Abbreviate, Space, StringLiteral(0), Space, By, Space, Identifier(0), FullStop, LineFeed, Declare, Space, StringLiteral(1), FullStop, LineFeed, Connect, Space, StringLiteral(2), Space, And, Space, Identifier(1), FullStop, LineFeed]);' >> bug.rs
moe bug.rs
```

### Detailed Description

At the moment, I am working on a coding language to describe graphs:  the Aeruginous Graph Description (AGD).  Its compiler shall read a given source file, turn it into tokens, turn those tokens into a graph, and draw that graph.  This is the repository:  https://github.com/kevinmatthes/aeruginous-rs.

The compiler does not work entirely, yet, but it can already turn a source file into tokens.  To make sure that the compiler creates the correct tokens, I created a unit test with a short source file of my new language:

```
(This is a sample AGD file.)

Abbreviate "et cetera" by etc.
Declare "etc".
Connect "etc" and etc.
```

When I defined the expected tokens in an assertion (see above in the steps to reproduce), I decided to enter the whole assertion in one line and make `rustfmt` care for the formatting; I assume that this is a common use case of text editors and source code formatting tools.  I noticed that the Rust syntax highlighting did not work as expected on that particular line -- but only if it is really just one line.  After running `cargo fmt`, the bug disappeared.

That particular line suffices to make the bug appear, so I extracted it and reverted the formatting to ensure the bug would show up.  It looks like a visual issue, at first, but when attempting to delete all characters beginning in the left-most column, the whole editor will break due to an invalid index.

When pasting text into the terminal using the terminal's shortcut therefore, Moe usually has wrapped lines, at first.  But there was never such a behaviour.  Thus, I am unsure which particular configuration in my assertion caused this bug to become visible because I do not know how to reproduce with other Rust code.  Hence, I decided to describe the issue with the coding language during whose development it appeared first.

**Comment by fox0430** [comment]
## Note

### Stack trace
```
/home/fox/git/moe/src/moe.nim(89) main
/home/fox/git/moe/src/moepkg/mainloop.nim(404) editorMainLoop
/home/fox/git/moe/src/moepkg/editorstatus.nim(723) update
/home/fox/git/moe/src/moepkg/viewhighlight.nim(372) updateHighlight
/home/fox/git/moe/src/moepkg/viewhighlight.nim(150) highlightPairOfParen
/home/fox/git/moe/src/moepkg/gapbuffer.nim(162) []
/usr/lib/nim/system/assertions.nim(38) failedAssertImpl
/usr/lib/nim/system/assertions.nim(28) raiseAssert
/usr/lib/nim/system/fatal.nim(54) sysFatal
Error: unhandled exception: /home/fox/git/moe/src/moepkg/gapbuffer.nim(162, 11) `0 <= index and index < gapBuffer.size` Gapbuffer: Invalid index. index = -1, gapBuffer.size = 2 [AssertionDefect]
```

**Comment by fox0430** [comment]
Fixed the crash bug (#1714) but the highlight is still not working.

**Comment by fox0430** [comment]
The highlight bug seems to occur probably when the value of `currentLineColorPair` in `editorstaus.update` exceeds 256.
Fixing this can be a bit of a pain...

**Comment by fox0430** [comment]
Close this issue and open a new issue for the highlight bug.
