### ISSUE TITLE
[Discussion] Scriv Fragment Creation

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1722]
@fox0430

In the Scriv repository, a user suggested the introduction of an interactive mode for `scriv create` such that one could select the category for which one is about to introduce changes.  This would be a great chance to minimise the file size of the resulting fragments but I am also afraid that this new mode might replace the current behaviour of being non-interactive such that any automation relying on the non-interactive behaviour would break.  This would also include the Scriv fragment creation Action this repository uses.  Although I realise that the pure suggestion of an interactive mode does not necessarily imply its implementation, I would like to discuss the possible options with you how the resulting issues might be best avoided, anyway.

One option might be to pin the Action to the latest version of Scriv which still uses the non-interactive behaviour but this might lead to vulnerabilities in the long term as I would rely on a version which is no longer maintained.  For this reason, that should not be preferred solution.

Instead, I created a workaround for the creation of a Scriv fragment.  The workaround is general enough to not necessarily be limited to Scriv.  The approach is that the desired fragment is generated from the commit messages of the current branch.  The application implementing this workaround reads the commit messages and extracts the items for the fragment which is created in a way compatible with Scriv.  Thus, the `scriv collect` step in the release preparation workflow would still work without any trouble.  Furthermore, one does not need to take care about the fragment's contents anymore as they are generated from the commit messages which is a great improvement regarding time efficiency.

In general, would you be interested in giving this workaround a try?

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you for your suggestions. It seems good. I want to try it.

**Comment by kevinmatthes** [comment]
@fox0430

Okay!

First of all, you need to install the application implementing this workaround, `aeruginous`, from the Rust package registry.  As its new mode, the workaround I wrote about in the initial comment, is not released as stable, yet, you will need to install the latest nightly version using this command:

```bash
cargo install --git https://github.com/kevinmatthes/aeruginous-rs
```

If you should not already have Rust set up on your machine, you can find the installation instructions here:  https://github.com/rust-lang/book/blob/main/src/ch01-01-installation.md.  Aeruginous comes with many useful utility modes and further ones are planned, so it is worth an installation.  You can remove it from your system with `cargo uninstall aeruginous`, followed by the Rust removal, at option, as described in the above installation instructions.

Next, you can test the workaround mode with the main branch of this repository.  Just execute the following command.

```bash
aeruginous comment-changes -d \/
```

You will receive a symbolic / sample Scriv fragment which will be saved in the repository root.  The `-d` option controls the delimiter; to set `changelog.d/` as output directory, you can use `-o changelog.d/`.  Finally, you can limit the number of commits to browse with `-n`, followed by an integer.

The idea is that you use a certain delimiter in your commit messages (in the first paragraph, the "summary", to be more precise) in order to separate the Scriv category from the category entry.  The example uses `/` which occurs in numerous commits, so you can limit the count of commits to browse with `-n` or use a rather unique separator like `::=` or `+=` for new commits.  The reason for this design is that the `comment-changes` mode of Aeruginous shall not be limited to work exclusively with Scriv and thus needs to be independent of its configuration file.  There is also an example in the README of Aeruginous, see https://github.com/kevinmatthes/aeruginous-rs#comment-changes.

To test this workaround in production, just name your commits accordingly and run `aeruginous comment-changes` before creating the PR of an active branch.  If this implementation is convenient for you, we can switch to Aeruginous for the Scriv fragment creation.  The next stable release containing this mode is planned for the end of the next week, so downloading the application from the registry for running it within a workflow would be possible, then, as well (although the installation might require a little more time than Scriv's, I assume).

If you should run into problems with Aeruginous, feel free to create an issue in its repository, https://github.com/kevinmatthes/aeruginous-rs.

**Comment by kevinmatthes** [comment]
@fox0430

I just finished the work on a workflow applying the workaround.  Here are some references:

- the workflow file:  https://github.com/kevinmatthes/aeruginous-rs/blob/main/.github/workflows/comment-changes.yml
- a PR which contains the results of the workflow:  https://github.com/kevinmatthes/aeruginous-rs/pull/189

The workflow itself is not that surprising despite the `fetch-depth` during the checkout.  `actions/checkout` will only return you the latest commit, by default.  This is not only *not* what you wanted, this will also cause Aeruginous to exit with an error as the sole commit checked out will point to another commit which is not visible.  You need to set `fetch-depth` to `0` to check out all commits of the whole repository which are accessible from the latest one.

When you apply this workaround in one of your own repositories, you are free to choose any delimiter.  In my repository, I usually use the Backus-Naur form assignment as this is rather unlikely to appear in any PR title.  Furthermore, you can set the trigger conditions to the PR creation, for example, such that your CI will create your CHANGELOG fragment for your.

Regarding the elapsed time, the Aeruginous approach -- at least in its very own repository -- takes about one minute more than the Scriv fragment creation Action.  In my opinion, the gained comfort of letting the CI document the changes is it definitely worth to wait one minute longer because you do not even need to care about the CHANGELOG fragment creation and population at all (despite counter-checking that all generated entries are still valid).

What do you think about the performance and the workflow design?  Furthermore, did you have a chance to test Aeruginous yourself, yet; did you encounter any problems?

**Comment by fox0430** [comment]
@kevinmatthes 

I tested it and I think it looks good workflow.  For performance, It will take some time to install it (About under 3 minutes) on Actions, but the cache may solve it.
Anyway, I will merge this workflow soon.

**Comment by fox0430** [comment]
@kevinmatthes 

One thing I've been wondering about is how do you link to PRs and issues? 

Like this
```
.. _#xxx: https://github.com/fox0430/moe/issues/xxx
.. _#xxx: https://github.com/fox0430/moe/pull/xxx
```

Is the assumption that links will not be used?

**Comment by kevinmatthes** [comment]
@fox0430

I was also thinking about this point during the development.  The current approach regarding Moe's Scriv policy as a use case is that one needs to wait for the exact PR number, anyway, so there is definitely going to be an edit of the created fragment.  When I created my PRs for changes to Moe, I tried to predict the next PR's number based on the recent issues and PRs such that I would not need to wait for the new PR being created -- but I also sometimes failed because there was another issue or PR raised before I could finish my submission.

But I also need to make some changes to the logic of the change commenting, so I will also add a feature for the link resolution.  For the PR number prediction, I cannot offer you an appropriate solution as an implementation in Aeruginous itself but we could do the following.  I know that there is an Action to determine the number of the current PR, so the fragment could be created with a placeholder, something like `pr-number`, for instance, and after the fragment was created, we figure out the PR number and run a sed command on the fragment to replace `pr-number` with the actual number *before* pushing the fragment to the branch.  Unfortunately, I forgot the name of that Action but I will try to search for it, anyway; I will tell you which Action it is when I find it.

The next step for me is to add the link resolution and to fix the bug I found in the logic.  Please wait with merging #1723 until I released the next stable version of Aeruginous within the next days because there might be changes to the calling semantics.  If so, I will request changes on #1723 with a concrete suggestion of how to fix the call.

**Comment by fox0430** [comment]
@kevinmatthes 

Okay. Thank you for the details. I wait to solve it.
