### ISSUE TITLE
Failed to update cursor position

### ISSUE THREAD

**Issue by marwal-88** [fox0430/moe#1741]
### Version

Nightly

### Category

Minor — The software basically does what it should do but there might be improvements.

### Steps to Reproduce

1. start moe with cmd 'moe'
2. press Shift+H
3. See screen fill up with sysFatal / unhandled exception etc.

### Detailed Description

output:
atal.nim(54)            sysFatal
                                Error: unhandled exception: cursor.nim(55, 13) `success` Failed to update cursorPosition: (y, x) = (0, -1), originalLine = [0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], start = [0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], length = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], lines = [], height = 25, width = 84 [AssertionDefect]

---------------------------------------------------
I'm using Linux.. Manjaro.
Terminal emulator: Alacritty
moe downloaded with nimble install moe@#head

**Comment by fox0430** [comment]
@marwal-88 

Thank you for the bug report. I will fix it soon.
