### ISSUE TITLE
[Bug Report] Incorrect Colour Mapping on Konsole

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1751]
### Version

Nightly

### Category

Visual ─ Output is hardly readable or not uniformly formatted.

### Steps to Reproduce

The bug always occurs with using either `example/moerc.toml` or the result of `moe --init` as configuration and KDE Konsole as terminal.

### Detailed Description

The terminal background colour is mapped to #F67400.  The default background colour of KDE Konsole is #232627.  Other colours are mapped incorrectly, as well, making the output hardly readable.

![Screenshot_20230707_153637](https://github.com/fox0430/moe/assets/92332892/eaa8c961-79b8-44fa-bd1c-b51b80e419fb)

**Comment by kevinmatthes** [comment]
I updated my installation of Moe today so I did not notice the bug earlier.  I assume that it is related to the introduction of the new colour model.

**Comment by kevinmatthes** [comment]
I just verified my assumption:  the bug begins with commit 7addfd2f876cc690b7c7c4c54fa1760265ff1179, i.e. the merge commit of the 24 bit and hex colours.  A workaround is to just use the build as of 57f76aa0cd075d42ec92b4963c659ce300f34bb1 which does not have the new model, yet.

**Comment by fox0430** [comment]
@kevinmatthes 

hmm... It may be the Konsole issue.
I don't know why, but Ncuese's `init_color` doesn't seem to work properly on Konsole.
I will research Konsole.

### Xterm
![xterm](https://github.com/fox0430/moe/assets/15966436/4c4b0afb-af29-4d01-922f-a72fffada34c)

### Gnome Terminal
![gnome](https://github.com/fox0430/moe/assets/15966436/053c4c45-0cc6-41fb-8347-b971eef2ee56)

### Alacritty
![alacritty](https://github.com/fox0430/moe/assets/15966436/5175b38f-6974-4959-b4c2-90f60a994f29)

### Konsole
![konsole](https://github.com/fox0430/moe/assets/15966436/cbde3452-c904-4941-b262-804f04116401)

### `init_color` test
Run this code on Konsole.
```nim
import pkg/ncurses

initscr()
startColor()

let exitCode = init_color(1, 0, 0, 0)

endWin()

assert 0 == exitCode
```

```
$ TERM=konsole-256color

$ nim c -r test.nim
/home/fox/test.nim(10) main
/home/fox/.choosenim/toolchains/nim-1.6.14/lib/system/assertions.nim(38) failedAssertImpl
/home/fox/.choosenim/toolchains/nim-1.6.14/lib/system/assertions.nim(28) raiseAssert
/home/fox/.choosenim/toolchains/nim-1.6.14/lib/system/fatal.nim(54) sysFatal
Error: unhandled exception: /home/fox/test.nim(10, 8) `0 == exitCode`  [AssertionDefect]
```

**Comment by fox0430** [comment]
@kevinmatthes 

I will add a workaround for this issue  (#1752) .
You can set a `colorMode` on your configuration file.

If you have any other comments or questions please let me know.

### Konsole
![colormode](https://github.com/fox0430/moe/assets/15966436/70412f91-7bfc-4ffc-ab30-7ae831760463)

**Comment by kevinmatthes** [comment]
@fox0430

Thank you for fixing the bug!  The workaround works perfectly fine for me, so this issue is basically resolved, from my point of view.

One last thing might be to add a section on platform / terminal specific behaviour / settings to the documentation where the recommended value for `standard.colorMode` for KDE Konsole is explained.  What do you think about this?

**Comment by fox0430** [comment]
@kevinmatthes 

Good idea, I will add it to the doc.
