### ISSUE TITLE
Ncurses crashes upon initialization

### ISSUE THREAD

**Issue by C-NERD** [fox0430/moe#1803]
### Version

v0.3.0

### Category

Major — The software does not fulfill the task it is designed for.

### Steps to Reproduce

1 clone the latest commit of moe from github
2 compile with either `nimble release` or `nimble debug`
3 attempt to open a file with moe

### Detailed Description

When attempting to open a file with moe. Moe responded with an error
```fish
Init Ncurses color failed: (r: 973, g: 961, b: 890): Exit code: -1
fatal.nim(53)            sysFatal
Error: unhandled exception: no exception to reraise [ReraiseDefect]
```
Note that my config file was generated by moe using the `moe --init` command

**Comment by fox0430** [comment]
@C-NERD 

Thank you for the bug report.
Can you tell me what OS and terminal you're using?

And, please try this configuration.
```
[Standard]
colorMode = "256"
```

See also [Platform / Terminal](https://github.com/fox0430/moe/blob/develop/documents/platform_terminal.md)

**Comment by C-NERD** [comment]
I am on arch linux using alacritty as terminal.
Also I tried using
```toml
[Standard]
colorMode = "256"
```
and here is the error I got
```fish
Init Ncurses color pair failed: (pair: 1, fg: 255, bg: 0): Exit code: -1
fatal.nim(53)            sysFatal
Error: unhandled exception: no exception to reraise [ReraiseDefect]
```

**Comment by fox0430** [comment]
@C-NERD 

Hmm... I also usually use Arch and Alacritty. so it should work...
What is your `$TERM`? Other than `xterm-256color` may not work.

**Comment by C-NERD** [comment]
Result from running `echo $TERM`
```fish
cnerd@cnerd ~> echo $TERM
tmux-256color
```

**Comment by fox0430** [comment]
@C-NERD 

Thank you. Reproduced in my environment. `tmux-256color` seems to be the cause.
Use `xterm-256color` please. Then it will work on tmux.

**Comment by C-NERD** [comment]
Ok it works when I set TERM = "xterm-256color", Thanks.
