### ISSUE TITLE
[Bug] Occasional Crash on `:deleteTrailingSpaces`

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1849]
### Version

moe v0.3.0

Git hash: e4059f17ab837dfe321dd12148617e52e38d8248
Build type: Release

### Environment

OS:  Debian 11
Terminal:  KDE Konsole

### Category

Major — The software does not fulfill the task it is designed for.

### Steps to Reproduce

1. `echo '  ' > test.txt`
2. `moe test.txt`
3. Go to the very end of the first line.
4. `:deleteTrailingSpaces`
5. Crash.

### Detailed Description

This bug only shows up when the cursor is set to a character which would be removed ***and*** the cursor is *not* set to the first column of the current line, i.e., if `test.txt` from the reproduction above would have been created using `echo ' ' > test.txt` (1 space character instead of at least 2), the bug would not have shown up.

Just a silly idea for a workaround:  setting the cursor to the start of the current line before removing all trailing characters?  I assume the bug is related to the cursor position which becomes invalid when the spaces are removed.  Users might consider it annoying to have to move their cursors back to its original position after deleting the trailing spaces but as a workaround for the crash, at least I would consider this solution acceptable as significant loss of progress due to the crash can be prevented that way.

**Comment by fox0430** [comment]
@kevinmatthes 

I will add processing to move to the end of the current line when the number of characters on the current line is smaller than the cursor after deleting trailing spaces.
