### ISSUE TITLE
[Bug] Crash on Viewing GPL-3.0 License File

### ISSUE THREAD

**Issue by kevinmatthes** [fox0430/moe#1850]
### Version

moe v0.3.0

Git hash: e4059f17ab837dfe321dd12148617e52e38d8248
Build type: Release

### Environment

OS:  Debian 11
Terminal:  KDE Konsole

### Category

Major — The software does not fulfill the task it is designed for.

### Steps to Reproduce

1. Navigate to any directory containing a GPL-3.0 license (named `LICENSE`, in the following).
2. `moe LICENSE`
3. Scroll down about two screen pages using arrow keys and / or mouse input.
4. Scroll up to the very first line using arrow keys and / or mouse input, again.
5. Crash.

### Detailed Description

The crash information will tell you something about `Invalid parentheses: L [AssertionDefect]`.  This reproducibly refers to line 41 of the GPL-3.0 license which is defined as follows:

```
(1) assert copyright on the software, and (2) offer you this License
```

I assume this bug is related to some tokenisation logic as the crash information refers to the lexical structure of the shown file.

**Comment by fox0430** [comment]
@kevinmatthes 

Can you reproduce 100%?  I reproduced it only once. I am certain this is a valid bug but I can not reproduce it every time.

### My steps
1. `cd moe`
2. `moe LICENSE`
3. `Ctrf-f`, `Ctf-f`, `Ctf-f` - Scroll down 2 pages.
4. Continue to press `k` - Scroll up to the first line.

**Comment by kevinmatthes** [comment]
@fox0430

Yes, it happens every time on my machine.  I even found a faster way to make the editor crash:

1. `cd moe`
2. `moe LICENSE`
3. `:600` (or any other line outside the current viewport)
4. `:41` (it *must* be this line)
5. Crash.

This gives:

```
Error: unhandled exception: unicodeext.nim(314, 17) `false` Invalid parentheses: L [AssertionDefect]
```

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you! 

It seems to be related to the size of the terminal and does not crash if it is small.
