### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by X-Ninja-dev** [fox0430/moe#1881]
### Version

v0.3.0
Build type: Release

### Environment

WIndows 11
Powershell
WSL2 - Ubuntu 22.04.2 LTS

### Category

Major — The software does not fulfill the task it is designed for.

### Steps to Reproduce

# Bugs
- Any kind of attempt to switch buffer results in buffers with files that are half deleted.
  The same goes if using :e <filename> to open a file.
  and :ls
  After having open another buffer as described above moe crashes on a 'out of range' if
  cursor is moved to the end of the file

- visual select some lines going from higher to lower line numbers and press 'd' to delete can crash moe
  nim(53)            sysFatal
  Error: unhandled exception: gapbuffer.nim(142, 11) `0 <= index and index < gapBuffer.size` Gapbuffer: Invalid index. index = 11, gapBuffer.size = 11 [AssertionDefect]

- change inside word (c i w) deletes the word before the word under the cursor
  if the ccursor is on the first char

  please delete this word
  (c i w) with the cursor on 'w' in word gives this result
  please delete word

- ctrl v pastes in windows under WSL2 instead of going into Visual Block mode

# Missing commands
- delete inside word
  d i w

- delete/change to char
  d/c t (char)

- delete/change to but including char (f: find)
  d/c f (char)

# Suggestet commands
- ctrl n to open the file tree

### Detailed Description

I think the above should describe the bugs but please ask me if you need more in-depth information or if you need me to try something out.

I'm guessing that I might be getting all these bugs because I'm on Windows under WSL2 as I can understand that not much testing has gone into Windows. But I'm also sure a few of them are pretty straightforward to fix :-)

I'll keep testing on Windows 11 under WSL2 and we'll see what solutions we can come up with over time :-)

**Comment by fox0430** [comment]
@X-Ninja-dev 

Are you using the [latest release](https://github.com/fox0430/moe/releases/tag/v0.3.0)? If so, try head (latest develop branch), please.
I planning to release a new version soon, but the current [release](https://github.com/fox0430/moe/releases/tag/v0.3.0) is very old...

**Comment by X-Ninja-dev** [comment]
When I installed it I went for the release version, but during installation, it prompted me that the release version wasn't available so it changed to head.

But I'll give it a try tomorrow and see if it makes a difference

**Comment by X-Ninja-dev** [comment]
Just installed 'head' instead and it is definitely not the version I was running. Some of the bugs are fixed and I'll get around to testing all off them (have a long list I haven't put here) :-)

BUT

there is one BIG bug. If I open it with "moe ." to open it up in that directory as I did before, it completely "crashes" my terminal. The cursor is gone and it writes things all over the screen and doesn't execute any of the commands.

`options.nim(230) get Error: unhandled exception: Can't obtain a value from a  'none' [UnpackDefect]`

**Comment by X-Ninja-dev** [comment]
Oh,, and I don't much care for the blue syntax highlighting in the 'head' version. I'll look into changing it when I have time

**Comment by fox0430** [comment]
@X-Ninja-dev 

> Just installed 'head' instead and it is definitely not the version I was running. Some of the bugs are fixed and I'll get around to testing all off them (have a long list I haven't put here) :-)

Thank you for trying head. Currently, the head is quite better than the latest release.

> there is one BIG bug. If I open it with "moe ." to open it up in that directory as I did before, it completely "crashes" my terminal. The cursor is gone and it writes things all over the screen and doesn't execute any of the commands.

Oh... It's a critical bug. I haven't opened directories recently so I didn't notice...  I'll fix it right now.

**Comment by X-Ninja-dev** [comment]
##Update on the bugs

- Switching buffer with e: now works. :ls shows the open buffers but doesn't switch to the chosen buffer. :bprev crashes Moe

- Using visual line to choose lines and delete them doesn't seem to crash it anymore

- change inside word (c i w) still deletes the word before the word under the cursor if the cursor is on the first char. I took a quick look at the code and the bug might be found here in line /normalmode.nim - line 338 where there is a call to .moveToBackwardWord before deleting the word. If /movement.nim - moveToBackwardWord() does what I think it sounds like it makes sense that it will jump to the previous word if the cursor is on the first letter of the current word?

`elif key == ru'w':
    # Delete current word and enter insert mode
    if oldLine.len > 0:
      currentBufStatus.moveToBackwardWord(currentMainWindowNode)
      status.deleteWord
    status.changeModeToInsertMode`

- ctrl v still pastes in windows under WSL2 instead of going into Visual Block mode

Hope this is helpful

NB. I really need the goto char t feature so I can do ct(x) dt(x). If you don't have time then maybe point me in the right direction so I can start implementing some of the features I need myself.

And I really would like to be able to change the syntax highlighting back to the release version :-)

**Comment by X-Ninja-dev** [comment]
new and vnew crashes the editor and the terminal in my setup.

`fatal.nim(53)            sysFatal
 2 import random             Error: unhandled exception: index 1 not in 0 .. 0 [IndexDefect]`

**Comment by X-Ninja-dev** [comment]
Do you want me to put new bugs I run into here in the issue or would you prefer I open a new one every time?

**Comment by fox0430** [comment]
@X-Ninja-dev 

Thank you reports. Personally, I want to open a new one.

**Comment by fox0430** [comment]
@X-Ninja-dev 

> Switching buffer with e: now works. :ls shows the open buffers but doesn't switch to the chosen buffer. :bprev crashes Moe

`:ls` is a correct behavior. It's only display, What you are looking for is probably `:buf`. But I noticed broke it... I'll fix it.

> ctrl v still pastes in windows under WSL2 instead of going into Visual Block mode

It should work fine on Linux. I don't know Powershell and Windows terminal.  But I found an issue where `Ctrl-v` does not work on Windows terminlal. Does Vim's `Ctrl-v` work?

https://stackoverflow.com/questions/61824177/visual-block-mode-not-working-in-vim-with-c-v-on-wslwindows-10

**Comment by fox0430** [comment]
@X-Ninja-dev 

>  :bprev crashes Moe

Can you explain the steps for the crash?

**Comment by X-Ninja-dev** [comment]
> It should work fine on Linux. I don't know Powershell and Windows terminal. But I found an issue where `Ctrl-v` does not work on Windows terminlal. Does Vim's `Ctrl-v` work?

No. I just checked it also doesn't work in Vim neither in Windows nor WSL2 (Ubuntu). I'm back on Windows for the first time in a long time so I have been using VS code with Vim keybindings and there it works so that's what I was thinking about.

Visual Block is super useful though so another keybinding for it would be sweet

**Comment by X-Ninja-dev** [comment]
> @X-Ninja-dev
> 
> > :bprev crashes Moe
> 
> Can you explain the steps for the crash?

- Open a file
- Open another file (:e FILENAME)
- :bprev

**Comment by fox0430** [comment]
@X-Ninja-dev 

I understand right now. indeed it crashes after displaying. Thank you.

**Comment by fox0430** [comment]
@X-Ninja-dev 

> change inside word (c i w) still deletes the word before the word under the cursor if the cursor is on the first char. I took a quick look at the code and the bug might be found here in line /normalmode.nim - line 338 where there is a call to .moveToBackwardWord before deleting the word. If /movement.nim - moveToBackwardWord() does what I think it sounds like it makes sense that it will jump to the previous word if the cursor is on the first letter of the current word?

Fixed


> NB. I really need the goto char t feature so I can do ct(x) dt(x). If you don't have time then maybe point me in the right direction so I can start implementing some of the features I need myself.

Completed


> And I really would like to be able to change the syntax highlighting back to the release version :-)

Please try this config. Probably the same colors.
```toml
[Standard]
theme = "config"

[Theme]
baseTheme = "dark"

foreground = "#ffffff"
background = "#000000"

keyword = "#87d7ff"
functionName = "#ffd700"
typeName = "#008000"
boolean = "#ffff00"
stringLit = "#ffff00"
specialVar = "#008000"
builtin = "#ffff00"
binNumber = "#00ffff"
decNumber = "#00ffff"
floatNumber = "#00ffff"
hexNumber = "#00ffff"
octNumber = "#00ffff"
comment = "#808080"
longComment = "#808080"
whitespace = "#808080"
preprocessor = "#008000"
```

Please let me know if there's anything else I missed.

**Comment by X-Ninja-dev** [comment]
Just tested and it looks like all commands are working. Thanks

I do have a longer list of missing commands if you want it :-)

The config didn't make any changes to the colors. I tried changing a few of the values myself and that did work so I can play around with it if you do not have the old config on hand.

**Comment by fox0430** [comment]
@X-Ninja-dev 

> I do have a longer list of missing commands if you want it

If you want commands, Please let me know. 


And I forgot the keybind for the visual block mode on Windows. Is there a keybind you want to assign? I'm thinking of assigning to `Ctrl-q`.

**Comment by X-Ninja-dev** [comment]
For Visual Block I was thinking ctrl+shift+v
It is close enough to the ctrl+v we have all used for years, it can still be done just by the left hand (I use it ctrl+shift+tab all the time) and it can also be used as the normal ctrl+v with the left hand and just push shift with the right hand.

The bad news:
It turns out that the brilliant people over at Microsoft have already made bindings for all ctrl+(x) where they add shift. I'm guessing it's because they want the keybinding to work even when people hit both ctrl and shift by mistake.

The good news:
Any keybinding command can easily be changed in the settings.json file so we can do whatever we want :-)

`{
   "command":
      {
         "action": "",
      },
      "keys": "ctrl+shift+v"
},`

And I just tested it, and with the above change in the settings.json file ctrl+shift+v actually goes into Visual Block mode in moe, so that is all we have to do :-D

Now the question is, do you make the change to the settings.json when moe is run or do you just instruct people to do it themselves?

We could even override ctrl+v when moe is run, but that would change it for, at least, all terminal interactions so I do not think that is the way to go.

Overriding it every time moe has focus could be an option.

And, you can still go with a completely different keybinding. alt+v would be right there and maybe feel natural for Mac users on a PC, but I do not know if alt+v already has a binding

**Comment by X-Ninja-dev** [comment]
My choice would be to ask the user on install if they are okay with overwriting ctrl+shift+v for use inside moe. I feel safe to say that everyone would answer yes because no one has ever used that key combination for anything and does not even know it exists.

**Comment by kevinmatthes** [comment]
Just for completeness:  I agree with asking before overriding the behaviour of Ctrl+Shift+V as this is an important change that requires the voluntary consent of each user.  But your estimation that this key binding would not be used at all does not seem quite correct to me as at least I myself use this binding every day to dump copied text sections into the terminal.  Thus, I would like to ask for leaving this decision up to the user but also to keep the current implementation of having this binding inserting copied text.

**Comment by X-Ninja-dev** [comment]
In what way does ctrl+shift+v differ from ctrl+v?

I can not see any difference in behavior here on windows 11 when pasting into cmd or powershell

**Comment by X-Ninja-dev** [comment]
Oh yeah, I've been away from real Linux for too long. In Linux, you have a bunch of different ways to paste into the terminal but almost none of the terminals accepts ctrl+v. I do not know if ctrl+shift+v works for pasting into most Linux terminals but that would be nice, cause for years I have been using clicking the right mouse button to paste :-)

But all that said, this whole Visual Block mode not working is only a Windows problem so, of course, only ask the user installing on Windows if they want the keybinding overridden. As for Windows I really do believe that no one knows that the keybinding even exists because it is just the same as ctrl+v

**Comment by kevinmatthes** [comment]
Indeed, Ctrl+Shift+V can be used in Linux terminals to paste copied text; Ctrl+Shift+C analogously is used for copying.  All terminals I encountered so far accept these two bindings and, if the shortcuts can be edited, offer these two as the default values.  There is also a Linux package to have mouse support in a TTY session, i.e. when no window server like X or Wayland is running, and this package as well accepts these bindings.

I am sorry that I forgot that your suggestion was related to Microsoft Windows, I usually use Linux and thus associated this conversation with my Linux point of view.

But as you suggested, maybe a system-dependent configuration could be the solution to this problem.  How about defining a default list of shortcut bindings for Microsoft Windows and turning them on by a new configuration entry, say `applyWindowsBindings`?  The pasting overriding might be the first entry and further ones could be added over time to ensure an optimal user experience on all systems.

**Comment by X-Ninja-dev** [comment]
I don't know how many Windows specific things/commands there are so I don't really know if it wards a specific Windows config, but it is certainly an option if there are several or if you expect more Windows specific things to sneak in down the line.

**Comment by fox0430** [comment]
I investigated how Windows users deal with this issue, and it seems that the most common method is to change the Terminal settings. But I think it would be a good idea to add settings for Windows.
For now, I'm thinking of adding the following settings.
```toml
[WindowsBindings]
# Enabling this setting allows you to switch to visual block mode with Ctrl-shift-v.
ctrl-shift-v = true
```

**Comment by fox0430** [comment]
Unfortunately, Maybe Ncurses cannot get `Ctrl`+`Shift`+`v`... I tried it but returned a code the same as `Shift`+`v`.
We need to find a way to get `Ctrl`+`Shift`+`v` or use another keybinding.

**Comment by X-Ninja-dev** [comment]
Not entirely sure what you mean.
On Linux, we do not need ctrl+shift+v. As I understand we already have ctrl+v.
On Windows (at least 10 and 11) the current implementation of Visual Block Mode already works with ctrl+shift+v if the command is just added in the settings.json file as an empty command

`{ "command": { "action": "", }, "keys": "ctrl+shift+v" },`

So my thought would be to edit the settings.json file once on installation or on each run.

**Comment by fox0430** [comment]
@X-Ninja-dev 

Okay. Please ignore. 

If you have no unfinished tasks here please close this issue.

**Comment by X-Ninja-dev** [comment]
Thanks for all the effort you put in here. I am now using moe as my primary editor and will be happy to continue to report on my findings and also just be part of the debate. I would love to contribute in actual code but I'm just not sure now is a good time for that.

**Comment by fox0430** [comment]
@X-Ninja-dev 

> I would love to contribute in actual code but I'm just not sure now is a good time for that.

Always welcome. If you have any questions, I will answer them to the best of my ability.
Of course, bug reports and opinions are also welcome.
