### ISSUE TITLE
Crash when opening dir

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#1882]
### Version

moe v0.3.0

Git hash: 55041477408fa515fb1f214a6ff246a385d32309
Build type: Debug

### Category

None

### Steps to Reproduce

1. `moe ./`

### Detailed Description

Lnik #1881

**Comment by X-Ninja-dev** [comment]
Tested it and it is working on my machine now 👍

**Comment by fox0430** [comment]
@X-Ninja-dev 

Please feel free to report bugs. I'll fix it as soon as possible.

**Comment by X-Ninja-dev** [comment]
This last one was quick I will give you that 🥇 :-)
