### ISSUE TITLE
Add support for copy & paste

### ISSUE THREAD

**Issue by dumblob** [fox0430/moe#392]
Copy & paste (by all 3 means: keyboard, mouse, command line) seems essential for good interoperability.

As inspiration how to achieve that on "all" platforms, refer to https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim .

**Comment by fox0430** [comment]
@dumblob 

Thank you feedback!
I will support the clipboard in the future.
Do you want mouse support too?

**Comment by dumblob** [comment]
Thanks for the quick reply :wink:.

>Do you want mouse support too?

I personally do not want/need mouse except for being able to paste with MMB or on Windows with right clicking in the terminal window and selecting paste from the menu :wink:.
