### ISSUE TITLE
Supports shell script

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#422]

**Comment by fox0430** [comment]
Syntax highlighting.

**Comment by kevinmatthes** [comment]
@fox0430

Which actual shells shall be supported in detail?  I assume definitely Bash as the syntax highlighting is triggered by the extension `*.bash` in addition to the generic extension `*.sh`.  I found a keyword list for many common shells, including Bash.  The question is merely whether I shall incorporate the support for the others, as well.  If so, I would also add support for their file extensions.

**Comment by fox0430** [comment]
@kevinmatthes 

I plan to support sh and bash.  Also, I personally want fish shell support, but it's a low priority.

**Comment by kevinmatthes** [comment]
@fox0430

Okay, I will restrict the keywords to Bash and Sh, then.  Shall I add the Bash configuration files to the file extensions triggers for the syntax highlighting, if appropriate?

**Comment by fox0430** [comment]
@kevinmatthes 

That's good. Yes please.
