### ISSUE TITLE
折り返されている行でのddコマンドについて

### ISSUE THREAD

**Issue by walkre-niboshi** [fox0430/moe#49]
折り返されている行でddコマンドを実行すると,行全体ではなく画面表示上での現在行が削除される.
実際のテキストファイル上での現在行が本来削除されるべき部分だと思うが,どのような仕様にするか.

**Comment by fox0430** [comment]
@walkre-niboshi 折り返されている行でddした場合は本来の行全体を削除するようにしようと思っています。
