### ISSUE TITLE
Unable to locate installed libncursesw.so

### ISSUE THREAD

**Issue by lf-araujo** [fox0430/moe#508]
Hi, thanks for this software!

It is not working on elementaryOS, as it is not locating libncursesw, which is currently installed.

![image](https://user-images.githubusercontent.com/10139950/74595898-27818380-5026-11ea-80ff-7190c6b4c0e5.png)

- How can I help debug this?

**Comment by fox0430** [comment]
@lf-araujo 

Thanks for the feedback !

https://github.com/rnowley/nim-ncurses/pull/17
Can this PR solve it?

**Comment by markpbaggett** [comment]
Maybe I'm doing something wrong, but I:

1. checked out the fix pr in nim-ncurses (#17)
2. recompiled / installed nim-ncurses
3. recompiled moe without pulling nim-ncurses backdown from github

Unfortunately, I'm still getting the same error. Am I doing anything wrong here or missing a step?

**Comment by fox0430** [comment]
@markpbaggett 

Thanks for the feedback.

What is the operating system using ?
Maybe additional package need to install.

**Comment by markpbaggett** [comment]
@fox0430:

`
cat /etc/os-release
`

NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Comment by fox0430** [comment]
@markpbaggett 

Thank you.
Ubuntu based distribution may require additional packages.
I will try too.

**Comment by fox0430** [comment]
@markpbaggett 

Can you try this?
```
sudo apt install libncurses5-dev
ln -s libncursesw.so.5 /lib/x86_64-linux-gnu/libncursesw.so
```

**Comment by lf-araujo** [comment]
I can confirm these steps solve the issue. Thanks!


-- 
Honorary Clinical Lecturer | Department of Psychiatry | The University 
of Melbourne
Post Doc | Center of Data and Knowledge Integration for Health (CIDACS) 
| Salvador | Brazil
p: +55 71 988477207 | http://go.unimelb.edu.au/y5yr On dom, fev 23,

**Comment by tobimensch** [comment]
I still encounter this issue on Fedora 31, even with all the suggested steps.

**Comment by fox0430** [comment]
@tobimensch 
Ok. I also try with Fedora.

**Comment by fox0430** [comment]
@tobimensch 

Try this
```
nimble install https://github.com/walkre-niboshi/nim-ncurses
nimble install moe
```

**Comment by tobimensch** [comment]
@fox0430 
works! Thank you. Can you put nim-ncurses as a dependency so that nimble will take care of this issue?

**Comment by fox0430** [comment]
@tobimensch 
Yes i did. Check #615 and https://github.com/walkre-niboshi/nim-ncurses/pull/1

**Comment by tobimensch** [comment]
@fox0430 
Great job! I like moe. The only suggestion so far is that moe should provide a help page, where you can learn all the vim keybindings/commands it is currently supporting in the editor.
```
:help
```
should get you a quick overview of everything that can be done with moe.

It's definitely a lightweight alternative to vim/nvim at this point.

**Comment by fox0430** [comment]
@tobimensch 

Thank you some feed back!

I plan to add help! ( #209 ). I want to implement it soon.
