### ISSUE TITLE
Can not install moe on a win10. "no such file or directory : ncurses.h"

### ISSUE THREAD

**Issue by 26awen** [fox0430/moe#567]
1. Build failed for 'moe@0.1.7', would you like to try installing 'moe@#head' (latest unstable)? [y/N]
2. If I chose "y", it will then give me the error message :"fatal error: ncurses.h: No such file or directory"

**Comment by fox0430** [comment]
@26awen Is ncurses installed ?

**Comment by 26awen** [comment]
@fox0430 Sorry I am not so familiar with such low-level things 😄 . But I can see nim-ncurses is required in the .nimble file and was installed successfully during the installation. 
Additionally, I can find a "ncurses.h" file in this path "C:\Users\myname\scoop\apps\gcc\8.1.0.0\opt\include\ncursesw\ncurses.h" （I have installed nim with scoop）., but I have no idea why it can not be found.

**Comment by fox0430** [comment]
Do you use windows (not WSL) ?

**Comment by 26awen** [comment]
@fox0430 Yes, as you said 😃  . NOT WSL

**Comment by fox0430** [comment]
@26awen 
Sorry. I have not tested on windows...
I'm testing on arch linux, ubuntu and WSL.

Maybe you can use it if you install PDCurses.

**Comment by 26awen** [comment]
@fox0430 Wont work with pdcurses.  I will try on a wsl later. thank you

**Comment by 26awen** [comment]
![image](https://user-images.githubusercontent.com/13186663/78354822-2826a700-75df-11ea-9d67-6aa78525e334.png)
@fox0430  Meet the same problem on a wsl (ubuntu 18.04) 😭 
After the failure to build the stable version, then choose to build the moe@head , show exactly the same error message as shown on win 10

**Comment by fox0430** [comment]
@26awen 
Have you checked https://github.com/fox0430/moe/blob/develop/documents/overview.md ?

**Comment by 26awen** [comment]
![image](https://user-images.githubusercontent.com/13186663/78356522-4c37b780-75e2-11ea-8a3a-a859c2192563.png)
@fox0430  I tried the code in the overview.md. Still can not install moe.(this snapeshot is the  second try. so it shows the prerequirements is a already satisfied)

**Comment by fox0430** [comment]
@26awen 
I reset WSL and try installing.

**Comment by fox0430** [comment]
@26awen 
Can you try this?
```
sudo apt install libncurses5-dev
nimble install moe
```

**Comment by 26awen** [comment]
@fox0430 It works with the new command you just given. 👍 👍 👍 

![image](https://user-images.githubusercontent.com/13186663/78364399-f4a04880-75ef-11ea-8095-8f6c1df5527e.png)

**Comment by fox0430** [comment]
@26awen 
Great !
This will be added to the documentation.
Thank you !

**Comment by 26awen** [comment]
@fox0430 My pleasure. 😄
