### ISSUE TITLE
stat->numOfLinesが正しい値になっていない

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#60]

**Comment by walkre-niboshi** [comment]
@fox0430 

行数を保持する変数についてはeditorStat.numOfLinesを廃止し,gapBuffer.sizeのみを使用する予定です.
なぜなら,これは常に真の行数を保持しているからです.

これ以外にも廃止する予定のeditorStatのメンバがいくつかあります.
詳しくは[moe.h](https://github.com/fox0430/moe/blob/new-view/moe.h)を参照してください("// obsolete"というコメントがついているメンバは廃止する予定です).

もしeditorStat.numOfLinesがどうしても必要ならば,numOfLinesはインスタンスではなく,gb->sizeへのポインタを保持するようにするのが良いと思います.いかがでしょうか.

**Comment by fox0430** [comment]
@walkre-niboshi なるほど。editorStat.numOfLines廃止了解です。
