### ISSUE TITLE
80 columns per line rule broken

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#634]
Hi @fox0430,

I skimmed through some of the code and as I like to use vertical split windows it became apparent very soon that the number of columns isn't limited in the sources.

For example in ui.nim, there's this:
```
insertTab(status.bufStatus[currentBufferIndex], status.workSpace[status.currentWorkSpaceIndex].currentMainWindowNode, status.settings.tabStop, status.settings.autoCloseParen)
```
This makes it more difficult to read or edit the code. Here's how one might format it instead:
```
insertTab(
  status.bufStatus[currentBufferIndex],
  status.workSpace[status.currentWorkSpaceIndex].currentMainWindowNode,
  status.settings.tabStop,
  status.settings.autoCloseParen)
``````
The above is what I'm currently doing in my code when I've calls with long arguments in them, that go beyond 80 columns. I put every argument on its own line, because I think this is more consequent,
than something like this, which is also an option:
```
insertTab(status.bufStatus[currentBufferIndex], 
  status.workSpace[status.currentWorkSpaceIndex].currentMainWindowNode,
  status.settings.tabStop, status.settings.autoCloseParen)
```
Whatever you decide looks best is okay with me.

I also found some long if conditions in editor.nim, like:
```
if currentLine >= bufStatus.buffer.high and currentColumn > bufStatus.buffer[currentLine].high: return 
```

There were longer ones, I've just taken the first one I saw as the example. This creates the same issues when working with split windows. Here's what one could do instead:
```
if (currentLine >= bufStatus.buffer.high and
    currentColumn > bufStatus.buffer[currentLine].high): return 
```

**Comment by fox0430** [comment]
@tobimensch 

Thank you for your advice.
I will fix code.

**Comment by tobimensch** [comment]
@fox0430 
Thanks for your work on this. Very good job.
