### ISSUE TITLE
Mode for merging status bar with ex command view

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#637]
Hi @fox0430,

thanks for merging my pull requests.

I'd like to see a setting for moe, where the status bar and the ex command view
get merged.
So when moe switches into ex command mode, the status bar gets overwritten by it,
and either you see a combined statusbar/excommandview
or the statusbar simply disappears, while being in excommand mode.

This is wanted, because some people don't see many reasons for wasting
vertical screen space.

**Comment by fox0430** [comment]
@tobimensch 

Good idea.
Let's add that feature !
