### ISSUE TITLE
Support for VSCode themes

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#646]
Reasoning:

A big userbase is needed to get a big number of themes from contributors.

Therefore it would be wise for moe to at least partially support
the theme format of one of the big editors/IDEs.

Because of that I'm currently working on vscode theme support for moe,
and will make a pull request for the partial support I have already implemented.

Why Vscode/VsCodium?

Their userbase is big and growing fast, there are tons of themes for it, and I happen to
use Vscode, so it was natural for me to want to have the same theme in moe and Vscode.

**Comment by tobimensch** [comment]
I've implemented initial support for this feature in #648.

**Comment by fox0430** [comment]
Completed
