### ISSUE TITLE
Directories before files in filer

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#653]
I want to discuss this first, so this is the question I have:

Should directories be listed before files in filer mode?
What would speak against this change?
Or could it be an option?

**Comment by fox0430** [comment]
@tobimensch 

It's a specification for reproducing netrw.
Not required.

**Comment by tobimensch** [comment]
Do you know what the reasoning in netrw is for not separating dirs/files in the listing?
Would you be against changing the default?

**Comment by fox0430** [comment]
@tobimensch 

I don't know...
It is unnecessary for practical use, so you can delete it.
