### ISSUE TITLE
Indention lines

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#655]
Something like this: https://github.com/Yggdroot/indentLine

```
if true:
   if true:
   |  echo "true"
   |  echo "also"
   |  if true:
   |  |  echo "even"
   |  |  echo "more"
```
A nicer character from unicode should be used instead of |.

I'm going to implement this, I just want to ensure that
1) moe doesn't already have something like it
2) this is welcome

It will be optional.

**Comment by fox0430** [comment]
@tobimensch 

This is welcome.
I want it too!

**Comment by tobimensch** [comment]
@fox0430 
It's working here now with 2 spaces for indents hardcoded, but I've to clean it up and add settings for it.

**Comment by tobimensch** [comment]
@fox0430 
Is there a global setting for ident width and kind (space vs tab)?
Or is that something that can be set for each file kind (nim vs python etc.)?
Is it tabStop?

**Comment by fox0430** [comment]
@tobimensch 

Indent setting is only [Standard] tabStop.

**Comment by tobimensch** [comment]
@fox0430 
See pull request #656

**Comment by tobimensch** [comment]
Thanks for merging!
