### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#671]
@fox0430 
When scrolling up or down using the j,k and also other cursor movements
of all kinds, the cursor regularly lags for a few seconds.

This is a major issue, as hardly anybody will use an editor in this condition
for serious work.

Some of it is highlighting related, there are other non-optimized path-ways
in the code though.

Maybe you can enlighten me on this issue.
What is the plan for making all navigation instant,
because that's how I think it should be.

Hopefully we can focus on this for the release after 0.1.9.

**Comment by fox0430** [comment]
@tobimensch 

Is it a few seconds delayed when scrolling ?
Does it happen even if I just keep scrolling ?

**Comment by fox0430** [comment]
@tobimensch 

Is it release build ?
Debug build has a big delay like you said...

**Comment by tobimensch** [comment]
@fox0430 
You're right! The release build is pretty good.
