### ISSUE TITLE
行の一番後ろでkey Down、key Upをした場合も常に一番後ろにカーソルが存在するようにする

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#69]

**Comment by walkre-niboshi** [comment]
おそらくvimの仕様は実際にはこのIssueのタイトルとは異なります.
観察から,vimはjキー/kキーによる行移動時の列の計算を以下のルールに基づいて行うようです.
- vimは列位置に燗する情報を2つ保持している.これを仮に列A,列Bと呼ぶことにする.列Aは単に現在列である.
- jキー/kキーによって別の行に移動したとき次のように列を更新する.
  - 列A = min(現在行の長さ-1, 列B) とする.
- hキー/lキーによって別の列に移動したとき次のように列を更新する.
  - 列Aと列Bを現在列に更新する.

vimの仕様に合わせて実装しますか?

**Comment by fox0430** [comment]
@walkre-niboshi vimの使用に合わせましょう

**Comment by walkre-niboshi** [comment]
@fox0430 👍

**Comment by walkre-niboshi** [comment]
moveFirstLine,moveLastLineについてはあえてvimとは異なる動作にしました(vimでは必ず0文字目に移動するがmoeでは現在列を保持する).

変更箇所が多いのでできれば動作の確認をお願いします.
