### ISSUE TITLE
Colors Are Off In Terminology Terminal

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#736]
I tested it on terminology 1.7.0 with a number of different terminology themes,
and it clearly doesn't know how to interpret the 256 color codes correctly.

I'm pretty sure that terminology has true color support, so we might fix this by
implementing true color support. https://github.com/fox0430/moe/issues/676

Maybe something is wrong with my settings, though I doubt that.

**Comment by fox0430** [comment]
@tobimensch 

I tried using the terminology v1.7.0 and it seems to be fine.

![Screenshot from 2020-06-30 02-11-46](https://user-images.githubusercontent.com/15966436/86035647-a6c4a080-ba77-11ea-8154-3b531be5380c.png)

What did you set $TERM ?

**Comment by tobimensch** [comment]
It now works for me also, don't know what went wrong there. Closing.
