### ISSUE TITLE
When highlighting the current word is enabled, don't highlight the word at cursor position

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#743]
As the title describes, I want this because I feel that your eyes are tracking the cursor anyway, so why
highlight the current word at the current cursor position. On top of that, depending on the theme settings
it can make the current word at the current cursor position more difficult to read and the flashing that happens
when the highlights appear/disappear also can be confusing.

So I'd like to see option to not highlight the current word at the current cursor position, I was about to implement this myself, but then had no time to do it correctly, and it looks like I'll not get back to it soon. So if someone else can implement the feature (if it's seen as a good idea, of course), I'd be thankful.

Greetings

**Comment by fox0430** [comment]
@tobimensch 

Please try latest develop branch
