### ISSUE TITLE
Handle writing/saving on non-existent path better

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#750]
Currently when opening a file(=> creating a new file) on non-existant path like

moe $HOME/.config/iammissing/myconfig.rc

You can edit the file just fine, and at first get no errors,
but when you want to save/write you get an error.

So instead, I think on writing/saving moe should check if the path to the file
exists, and if it doesn't exist, in my opinion it should ask the user a yes/no question like:
$HOME/.config/iammissing/ doesn't exist. Create it now? (y/n) [default: yes]

Hitting Enter or Y/y should make moe create the iammissing folder, and then of course save the
file, while n should abort the write.

It should work like mkdir -p, meaning if both .config and iammissing don't exist a Y/y answer
by the user should create any and all folders that are missing in the path.

**Comment by fox0430** [comment]
@tobimensch 

Good idea! I will implementation soon.

**Comment by tobimensch** [comment]
@fox0430 
Great! Looking forward to it.
