### ISSUE TITLE
Recent files selection

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#760]
This is something I often use in other editors, so I'd be disappointed if this was never getting added to moe.

Basically I want a filer like selection mode for the most recently opened files.

There is a freedesktop specification for Linux https://specifications.freedesktop.org/recent-file-spec/recent-file-spec-0.2.html , that hopefully works for most desktop environments. I suppose Windows and Mac also have something like it, so it should be supported, too. Personally I'm only using Linux though.

Unfortunately this specification seems to be out of date now.

On my system some recent files are found in:
.local/share/recently-used.xbel

But the spec says `The document should be stored in "~/.recently-used"`.

Also you'd have to investigate differences between how Gnome/KDE and lesser known desktops such as Enlightenment handle it. It might be a bit of a mess, but the feature should be worth the trouble.

I would like to open this selection mode with a command like:
```:recent```

**Comment by fox0430** [comment]
@tobimensch 

Ok. I try implement on v0.2.1
