### ISSUE TITLE
Make commands case insensitive

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#778]
So I wrote that this https://github.com/fox0430/moe/issues/777 would be my last issue for a while, and that was wrong, because I've another thing to discuss, so sorry, if you were hopeful that there were no more requests for today, I must destroy that hope. But this is really the last one. At least I hope so. :-)

In Nim, contrary to most programming languages, identifiers are case insensitive, which I began to appreciate after a while, it adds flexibility, and you can still stick to yourPreferedStyle if you want or need to.

And why should it matter if you type:
```:indentationLines off```
or
```:indentationlines off```

I ran quickly through the commands in my head, and I can't think of many use cases where you'd need a comMand and a command.

The only exception might be single letter commands that might be added to moe.

And Nim also makes an exception for the first character, so it distinguishes between x and X and word and Word. We should make that exception, too.

Are you with me on this?

**Comment by fox0430** [comment]
@tobimensch 

Ok. Thank you many request.
I think so, too.
