### ISSUE TITLE
Bug in new feature that creates directories when saving

### ISSUE THREAD

**Issue by tobimensch** [fox0430/moe#779]
I just installed glava for visualization of music.

And then opened its config with moe .config/glava/rc.glsl

The file opened fine and I could edit it.

But when I wanted to save it with :w it told me that .config/glava doesn't exist,
even though it clearly exists, is evidenced by the fact that the file in that directory was opened.

It offered me to create the directory, which I answered with y, but this doesn't matter,
as it shouldn't have offered me to create a directory that does already exist.

It didn't crash or anything like that, just annoyed me a little.

**Comment by tobimensch** [comment]
Hmm, okay this feature seems to be broken in more than one way.

When I cd'ed into .config/glava and then opened rc.glsl with moe rc.glsl
and then tried to save a change it also told me that ' ' doesn't exist. Create it now?,
however there's not directory, it's just a simple file in $PWD.

**Comment by fox0430** [comment]
I will fix it soon.

**Comment by fox0430** [comment]
@tobimensch 

Please try v0.2.0.1

**Comment by tobimensch** [comment]
@fox0430 
Better!

Thanks!
