### ISSUE TITLE
Quick run

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#784]
Features like vim-quickrun

**Comment by tobimensch** [comment]
This could replace some play.nim-lang.org use cases.

**Comment by fox0430** [comment]
@tobimensch 

This is nice.
I may also assign a keybind.
I have not decided the key assignment yet.

**Comment by tobimensch** [comment]
I'm used to F6 for running the current file with the VSCode Nim extension.
I don't know if it's good, but now I'm used to it.

**Comment by fox0430** [comment]
@tobimensch 

I see.
What do you think of ```Tab-r```?
Tab key is not normally used...

**Comment by tobimensch** [comment]
Couldn't that trigger CAPSLOCK though?

**Comment by fox0430** [comment]
@tobimensch 

How about enabling in normal mode only?
Are you using the Tab key in normal mode?

**Comment by tobimensch** [comment]
@fox0430 
No, you're right, it'd be possible. Tab is typically used for navigating between parts of an interface, Tab-r would break that expectation. So Tab-r gets a downvote from me, but I respect your decisions.

**Comment by fox0430** [comment]
@tobimensch 

Thank you for your opinion!
Ok. I changed my mind. I don't use tab key.

Off course, will be configurable in the future.

**Comment by tobimensch** [comment]
Can't wait to try this! Awesome work @fox0430 .

Keep up this pace and I won't miss vim/nvim in about a year.
