### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#830]
The cursor changes when opening moe, but no when closing. So the terminal cursor changes.

**Comment by tobimensch** [comment]
What terminal are you using?

Can you give detailed steps of what you did and the outcomes?

**Comment by fox0430** [comment]
@unihernandez22 

Please try set ```Standard.defaultCursor``` settings.
Do not support auto restore cursor shape yet.

**Comment by unihernandez22** [comment]
I had the problem on Peppermint Linux, Sakura is the terminal emulator. I think the best solution is don't change the cursor, like vim.

**Comment by unihernandez22** [comment]
> Please try ```Standard.defaultCursor``` setting.

Ahhh, ok.

**Comment by walkre-niboshi** [comment]
I think the better solution is to provide an option to disable the change of the cursor, like neovim(https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal).

**Comment by fox0430** [comment]
I will add the setting to disable the change of the cursor shape.
