### ISSUE TITLE
Tabs erasing

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#837]
When I erase a tab (2 spaces), I have to press backspace twice. The tabs have to be erased space by space.

**Comment by unihernandez22** [comment]
I think is good to configure tabs like vim.

`tabstop`
`softtabstop`
and
`shiftwidth`

**Comment by tobimensch** [comment]
What you want is similar to #751, which is adding a tab(width) by a single space key, but in the reverse direction.

**Comment by unihernandez22** [comment]
> What you want is similar to #751, which is adding a tab(width) by a single space key, but in the reverse direction.

No, that's not that I want. And, for the #751, why? If you can use `tab` instead?

**Comment by tobimensch** [comment]
> > What you want is similar to #751, which is adding a tab(width) by a single space key, but in the reverse direction.
> 
> No, that's not that I want. And, for the #751, why? If you can use `tab` instead?

Today seems to be the day where my words are getting taken out of context by everyone. I didn't write that you want #751, I wrote that there are commonalities between those features (one basically being the other in reverse).

As to why #751. Some people find the tab key uncomfortable to reach, I also frequently find it uncomfortable to reach.

**Comment by unihernandez22** [comment]
This issue still open? @fox0430 I think this is an important thing.

**Comment by fox0430** [comment]
@unihernandez22 

Yes. still open.
I want to work on it early.

**Comment by tobimensch** [comment]
> This issue still open? @fox0430 I think this is an important thing.

True.
