### ISSUE TITLE
Auto-indent and return

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#838]
When I press return, moe auto-indents the line, but if I want an empty line and I press return again, the indentation should be erased automatically.

**Comment by fox0430** [comment]
@unihernandez22 

Can you give me a simple step to reproduce?

**Comment by unihernandez22** [comment]
Only open a .nim file, and with active autoindent, you can write:

```
when isMainModule:
  continue
```

And then <return> <return> <return>

**Comment by unihernandez22** [comment]
The spaces created by the autoindent, will stay there

**Comment by fox0430** [comment]
@unihernandez22 

Ok. Thank you.

**Comment by unihernandez22** [comment]
And, another enhancement, when you finish a line with `:`, the auto-indent should indent the next line.

**Comment by fox0430** [comment]
@unihernandez22 

You're right. I will implement it soon.
