### ISSUE TITLE
Highlight other languages

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#843]
How can I add highlighting for other languages?

**Comment by fox0430** [comment]
@unihernandez22 

Currently, it is difficult to add support for new languages.
We are currently using the highlite module, and we need to create a new mechanism to add support for languages that the highlite module does not support.

**Comment by juancarlospaco** [comment]
Maybe copy the `highlite.nim` file to the repo and add languages there?, code is not too big was 1 file ~500 lines.

**Comment by fox0430** [comment]
@juancarlospaco 

Ok. Let's just go with that for now.

**Comment by unihernandez22** [comment]
> Maybe copy the `highlite.nim` file to the repo and add languages there?, code is not too big was 1 file ~500 lines.
> 

@fox0430 
Ok, I think after that we can have a dir on `~/.config/moe/highlight` and there files like `python.nim` so the user can add your own languages highlighting.

**Comment by fox0430** [comment]
@unihernandez22 

I don't know yet, but I would like to achieve that using NimScript.

**Comment by unihernandez22** [comment]
> I don't know yet, but I would like to achieve that using NimScript.

Yessss!! And the same for the config file, and the ex mode :wink: #840

**Comment by walkre-niboshi** [comment]
@juancarlospaco
> Maybe copy the highlite.nim file to the repo and add languages there?, code is not too big was 1 file ~500 lines.

This enables moe's own speedup of highlite.nim. This is something I've always wanted and I strongly support this suggestion!

**Comment by unihernandez22** [comment]
@fox0430 check https://github.com/unihernandez22/moe/tree/python-highlight

**Comment by fox0430** [comment]
@unihernandez22 

Great!

**Comment by unihernandez22** [comment]
@fox0430 
> Great!

If you want I can do a pull request

**Comment by fox0430** [comment]
@unihernandez22 

Yes, please!

**Comment by unihernandez22** [comment]
We need a plugin system, so the community can add support for other languages.
Moe needs a scripting language.

**Comment by fox0430** [comment]
@unihernandez22 

Ok... I will try to add support a scripting language to moe. (Maybe in v0.2.4)

**Comment by fox0430** [comment]
@unihernandez22 

Plugin system is very important. But, I want to provide built-in support for major languages.

**Comment by unihernandez22** [comment]
@fox0430 

Yeah, but we can't add support of all languages... So the community can support minor languages.
