### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#844]
When I add
```
[Theme]

statusBarInsertModeBg = "red"

statusBarVisualModeBg = "blue"

statusBarExModeBg = "pink"
```
to my ~/.config/moe/moerc.toml, the colors doesn't change. The only config that works is `statusBarNormalModeBg`.

**Comment by unihernandez22** [comment]
The bug isn't fixed...

**Comment by fox0430** [comment]
@unihernandez22 

Oops. I will check.

**Comment by unihernandez22** [comment]
Wait, the colors doesn't work if I have "pink" in anyone

**Comment by unihernandez22** [comment]
![image](https://user-images.githubusercontent.com/62044675/88334723-94e9bc80-cd08-11ea-8b72-12d5d5f25ea5.png)

And there is a part who doesn't change

**Comment by unihernandez22** [comment]
`develop` should be green too

**Comment by fox0430** [comment]
@unihernandez22 

Please try to use ```pink1```.
```pink``` does not exist.

**Comment by unihernandez22** [comment]
> ```pink``` does not exist.

Ok, that's the problem xD
It should show an error, not disable all the theme

**Comment by fox0430** [comment]
@unihernandez22 

You are right.
I will change to show an error message if loaded invalid settings.
