### ISSUE TITLE
Characters on filer mode

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#845]
![image](https://user-images.githubusercontent.com/62044675/88135079-95753c80-cbbc-11ea-9595-a2cb81626880.png)

**Comment by fox0430** [comment]
@unihernandez22 

This terminal emulator is supported UTF-8 (Emoji)?

**Comment by unihernandez22** [comment]
Yes, the terminal uses UTF-8 Unicode

And... What's the emoji font?

**Comment by unihernandez22** [comment]
Is there an option to disable emojis?

**Comment by fox0430** [comment]
@unihernandez22 

For example, Noto Emoji.

**Comment by fox0430** [comment]
@unihernandez22 

```
Is there an option to disable emojis?
```

Yes. Check ```Filer.showIcons```.

https://github.com/fox0430/moe/blob/4f99b80c09bceaccef634d2adb4ac3711921b79a/example/moerc.toml#L134

**Comment by unihernandez22** [comment]
> @fox0430
> Yes. Check `Filer.showIcons`.

Ok, thx.
