### ISSUE TITLE
normal modeへの切り替え

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#85]
normal modeに切り替えた際に瞬時にステータスバーの表示が切り替わらない

**Comment by walkre-niboshi** [comment]
何のモードからnormal modeに切り替えた場合に発生しますか?
ステータスバーの表示とは具体的には例えば何を指していますか?

**Comment by fox0430** [comment]
@walkre-niboshi insert modeからnormal modeにESCキーを押して切り替える際, 瞬時にステータスバーのモード表示がnormal modeに切り替わらず何かキーをもう一度押す必要がある
