### ISSUE TITLE
ExMode changes only after putting a char

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#856]
![image](https://user-images.githubusercontent.com/62044675/88334570-5bb14c80-cd08-11ea-9b8d-0fa476392ee6.png)

![image](https://user-images.githubusercontent.com/62044675/88334609-68ce3b80-cd08-11ea-9499-df1a34b92727.png)

**Comment by fox0430** [comment]
@unihernandez22 

Please try to set ```Theme.statusBarGitBranch``` and ```Theme.statusBarGitBranchBg```

**Comment by unihernandez22** [comment]
> @unihernandez22 
> 
> Please try to set ```Theme.statusBarGitBranch``` and ```Theme.statusBarGitBranchBg```

But, and the label of the mode? It changes after putting a char, and it should be when I put `:`

**Comment by fox0430** [comment]
@unihernandez22 

This is a bug. I will fix it.
