### ISSUE TITLE
Add vim's Shift+i in Visual Block mode

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#868]
![vimblockvisualmode-2020-07-24_14 14 56](https://user-images.githubusercontent.com/62044675/88417818-fec19f00-cdb8-11ea-8e83-d5262f7456ed.gif)

```
Ctrl + v                -> Visual Block
(I select the lines)
Shift + i               -> Goes to the first line, here I write
Esc                     -> Applies the changes to the first line, for the others
```

**Comment by unihernandez22** [comment]
@fox0430 
In moe, is there something like this, for commenting multiple lines at once?

**Comment by fox0430** [comment]
@unihernandez22 

Nothing for now. But, I will support multiple lines inserts with ```shift + i``` at least.
