### ISSUE TITLE
`x` in Visual Block mode

### ISSUE THREAD

**Issue by unihernandez22** [fox0430/moe#885]
![moeblockvisualmode-2020-07-28_14 05 04](https://user-images.githubusercontent.com/62044675/88698309-452a3d00-d0dc-11ea-98d8-0bbccd81c11e.gif)

```
fatal.nim(49)            sysFatal
Error: unhandled exception: gapbuffer.nim(142, 11) `0 <= index and index < gapBuffer.size` Gapbuffer: Invalid index. index = 4, gapBuffer.size = 3 [AssertionError]
```

When using `x` in visual block mode with more than one column selected

**Comment by tobimensch** [comment]
Can confirm.
